
########### food_pre2 - 19 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Tomato2 - object)
 	(SoapBottle1 - object)
 	(DishSponge1 - object)
 	(Lettuce2 - object)
 	(Spoon1 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Spoon2 - object)
 	(Pan1 - object)
 	(Pot1 - object)
 	(Cup1 - object)
 	(Cup2 - object)
 	(Mug1 - object)
 	(Apple1 - object)
 	(Lettuce3 - object)
 	(CounterTop1 - receptacle)
 	(Pan2 - receptacle)
 	(Cabinet1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Plate2 - receptacle)
 	(Microwave1 - receptacle)
 	(Cabinet2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(Bowl1 - receptacle)
 	(Pot1 - receptacle)
 	(Pan3 - receptacle)
 	(Bowl2 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Pan1 - receptacle)
 )
(:init 
 	(sliceable Tomato2)
 	(sliceable Lettuce2)
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Apple1)
 	(sliceable Lettuce3)
 	(heatable Tomato2)
 	(heatable Tomato1)
 	(heatable Cup1)
 	(heatable Cup2)
 	(heatable Apple1)
 	(coolable Tomato2)
 	(coolable Lettuce2)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Apple1)
 	(coolable Lettuce3)
 	(objectAtLocation SoapBottle1 Cabinet1)
 	(objectAtLocation Pot1 SinkBasin1)
 	(objectAtLocation Tomato1 Pan1)
 	(objectAtLocation Apple1 Pan2)
 	(objectAtLocation DishSponge1 Plate1)
 	(objectAtLocation Pan1 SinkBasin2)
 	(objectAtLocation Tomato2 Pot1)
 	(objectAtLocation Lettuce1 Plate2)
 	(objectAtLocation Lettuce2 Bowl1)
 	(objectAtLocation Cup1 CounterTop1)
 	(objectAtLocation Lettuce3 GarbageCan1)
 	(objectAtLocation Spoon1 Pan3)
 	(objectAtLocation Mug1 Cabinet2)
 	(objectAtLocation Cup2 Microwave1)
 	(objectAtLocation Spoon2 Bowl2)
 )
Output:
(:goal (and
                (isSliced Apple1)
                (inReceptacle Apple1 Plate2)
            )
        )