
########### food_pre2 - 7 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Cup3 - object)
 	(Fork1 - object)
 	(SoapBottle1 - object)
 	(PepperShaker1 - object)
 	(Mug2 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Ladle1 - object)
 	(Pot1 - object)
 	(Potato1 - object)
 	(Cup1 - object)
 	(Cup2 - object)
 	(Mug1 - object)
 	(Pan1 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Cabinet3 - receptacle)
 	(Cabinet1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Cabinet4 - receptacle)
 	(Microwave1 - receptacle)
 	(Fridge3 - receptacle)
 	(Fridge2 - receptacle)
 	(Cabinet2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(Pot1 - receptacle)
 	(Microwave2 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Apple1 - object)
 	(Plate1 - receptacle)
 )
(:init 
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Potato1)
 	(heatable Cup3)
 	(heatable Tomato1)
 	(heatable Potato1)
 	(heatable Cup1)
 	(heatable Cup2)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Potato1)
 	(objectAtLocation Pot1 Fridge1)
 	(objectAtLocation Fork1 Bowl1)
 	(objectAtLocation Mug1 Microwave1)
 	(objectAtLocation PepperShaker1 Cabinet1)
 	(objectAtLocation Cup1 Cabinet2)
 	(objectAtLocation Ladle1 CounterTop1)
 	(objectAtLocation Cup2 Microwave2)
 	(objectAtLocation Mug2 Fridge2)
 	(objectAtLocation ButterKnife1 Pot1)
 	(objectAtLocation SoapBottle1 Cabinet3)
 	(objectAtLocation Potato1 SinkBasin1)
 	(objectAtLocation Cup3 Fridge3)
 	(objectAtLocation Lettuce1 SinkBasin2)
 	(objectAtLocation Tomato1 GarbageCan1)
 	(objectAtLocation Pan1 Cabinet4)
 	(objectAtLocation Apple1 Bowl1)
 )
Output:
(:goal (and
        (isSliced Apple1)
        (inReceptacle Apple1 Plate1)
    )
)