
########### food_pre2 - 12 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Lettuce2 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Lettuce4 - object)
 	(Bowl1 - object)
 	(Ladle1 - object)
 	(Pot1 - object)
 	(Potato1 - object)
 	(Lettuce3 - object)
 	(Cup1 - object)
 	(Apple2 - object)
 	(Apple1 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Cabinet3 - receptacle)
 	(Cabinet1 - receptacle)
 	(CounterTop3 - receptacle)
 	(CounterTop2 - receptacle)
 	(Cabinet2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(SinkBasin3 - receptacle)
 	(Pot1 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Plate2 - receptacle)
 )
(:init 
 	(sliceable Lettuce2)
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Lettuce4)
 	(sliceable Potato1)
 	(sliceable Apple2)
 	(sliceable Apple1)
 	(sliceable Lettuce3)
 	(heatable Tomato1)
 	(heatable Potato1)
 	(heatable Cup1)
 	(heatable Apple2)
 	(heatable Apple1)
 	(coolable Lettuce2)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Lettuce4)
 	(coolable Potato1)
 	(coolable Apple2)
 	(coolable Apple1)
 	(coolable Lettuce3)
 	(objectAtLocation Tomato1 Plate1)
 	(objectAtLocation Bowl1 Cabinet1)
 	(objectAtLocation Cup1 Cabinet2)
 	(objectAtLocation Lettuce1 SinkBasin1)
 	(objectAtLocation Lettuce2 Fridge1)
 	(objectAtLocation ButterKnife1 CounterTop1)
 	(objectAtLocation Apple1 Plate2)
 	(objectAtLocation Pot1 SinkBasin2)
 	(objectAtLocation Ladle1 Cabinet3)
 	(objectAtLocation Lettuce3 CounterTop2)
 	(objectAtLocation Potato1 CounterTop3)
 	(objectAtLocation Lettuce4 Pot1)
 	(objectAtLocation Apple2 SinkBasin3)
 )
Output:
(:goal (and
        (isSliced Apple1)
        (isSliced Apple2)
        (inReceptacle Apple1 Plate1)
        (inReceptacle Apple2 Plate2)
    )
)