
########### food_pre2 - 3 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Pan2 - object)
 	(DishSponge1 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Bowl1 - object)
 	(Bowl2 - object)
 	(Plate1 - object)
 	(Potato1 - object)
 	(Egg1 - object)
 	(Mug1 - object)
 	(Pan1 - object)
 	(CounterTop1 - receptacle)
 	(Pan2 - receptacle)
 	(Cabinet1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Microwave1 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(SinkBasin3 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Pan1 - receptacle)
 	(Apple1 - object)
 	(Plate1 - receptacle)
 )
(:init 
 	(sliceable Egg1)
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Potato1)
 	(heatable Egg1)
 	(heatable Tomato1)
 	(heatable Potato1)
 	(coolable Egg1)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Potato1)
 	(objectAtLocation Bowl1 Microwave1)
 	(objectAtLocation Pan1 SinkBasin1)
 	(objectAtLocation Tomato1 CounterTop1)
 	(objectAtLocation Potato1 Bowl1)
 	(objectAtLocation DishSponge1 Pan1)
 	(objectAtLocation Lettuce1 Pan2)
 	(objectAtLocation Pan2 Cabinet1)
 	(objectAtLocation Bowl2 SinkBasin2)
 	(objectAtLocation Plate1 SinkBasin3)
 	(objectAtLocation Egg1 GarbageCan1)
 	(objectAtLocation Mug1 CounterTop2)
 	(objectAtLocation Apple1 GarbageCan1)
 )
Output:
(:goal (and
                (isSliced Apple1)
                (inReceptacle Apple1 Plate1)
            )
        )