
########### food_pre2 - 5 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Tomato2 - object)
 	(Fork1 - object)
 	(Bread1 - object)
 	(Tomato1 - object)
 	(Plate1 - object)
 	(Egg1 - object)
 	(Cup1 - object)
 	(Apple1 - object)
 	(SaltShaker1 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Cabinet1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Microwave1 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(Pot1 - receptacle)
 	(Pan1 - receptacle)
 )
(:init 
 	(sliceable Tomato2)
 	(sliceable Bread1)
 	(sliceable Tomato1)
 	(sliceable Egg1)
 	(sliceable Apple1)
 	(heatable Tomato2)
 	(heatable Bread1)
 	(heatable Tomato1)
 	(heatable Egg1)
 	(heatable Cup1)
 	(heatable Apple1)
 	(coolable Tomato2)
 	(coolable Bread1)
 	(coolable Tomato1)
 	(coolable Egg1)
 	(coolable Apple1)
 	(objectAtLocation Cup1 Cabinet1)
 	(objectAtLocation Apple1 Microwave1)
 	(objectAtLocation Tomato1 GarbageCan1)
 	(objectAtLocation Plate1 CounterTop1)
 	(objectAtLocation ButterKnife1 Plate1)
 	(objectAtLocation SaltShaker1 CounterTop2)
 	(objectAtLocation Bread1 Fridge1)
 	(objectAtLocation Egg1 Pan1)
 	(objectAtLocation Fork1 Pot1)
 	(objectAtLocation Tomato2 SinkBasin1)
 )
Output:
(:goal (and
                (isSliced Apple1)
                (inReceptacle Apple1 Plate1)
            )
        )