
########### food_pre2 - 14 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Spoon1 - object)
 	(DishSponge1 - object)
 	(Knife1 - object)
 	(PepperShaker1 - object)
 	(Knife2 - object)
 	(Apple1 - object)
 	(Apple3 - object)
 	(Ladle1 - object)
 	(Egg1 - object)
 	(Apple2 - object)
 	(Mug1 - object)
 	(Pan1 - object)
 	(Egg2 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Bowl5 - receptacle)
 	(Fridge1 - receptacle)
 	(Cabinet1 - receptacle)
 	(Microwave1 - receptacle)
 	(Mug2 - receptacle)
 	(Bowl4 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl2 - receptacle)
 	(Bowl1 - receptacle)
 	(Plate1 - receptacle)
 	(Microwave2 - receptacle)
 	(Plate2 - receptacle)
 	(Mug1 - receptacle)
 	(Bowl3 - receptacle)
 )
(:init 
 	(sliceable Apple3)
 	(sliceable Egg1)
 	(sliceable Apple2)
 	(sliceable Apple1)
 	(sliceable Egg2)
 	(heatable Apple3)
 	(heatable Egg1)
 	(heatable Apple2)
 	(heatable Apple1)
 	(heatable Egg2)
 	(coolable Apple3)
 	(coolable Egg1)
 	(coolable Apple2)
 	(coolable Apple1)
 	(coolable Egg2)
 	(objectAtLocation Pan1 CounterTop1)
 	(objectAtLocation Knife1 Bowl1)
 	(objectAtLocation Apple1 Microwave1)
 	(objectAtLocation Fork1 Bowl2)
 	(objectAtLocation Egg1 Bowl3)
 	(objectAtLocation Spoon1 Mug1)
 	(objectAtLocation ButterKnife1 Mug2)
 	(objectAtLocation Apple2 Bowl4)
 	(objectAtLocation Ladle1 Plate1)
 	(objectAtLocation Egg2 SinkBasin1)
 	(objectAtLocation Knife2 Plate2)
 	(objectAtLocation PepperShaker1 Cabinet1)
 	(objectAtLocation Mug1 Microwave2)
 	(objectAtLocation DishSponge1 Bowl5)
 	(objectAtLocation Apple3 Fridge1)
 )
Output:
(:goal (and
                (isSliced Apple1)
                (isSliced Apple2)
                (isSliced Apple3)
                (inReceptacle Apple1 Plate1)
                (inReceptacle Apple2 Plate1)
                (inReceptacle Apple3 Plate1)
            )
        )