
########### food_pre2 - 10 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Tomato2 - object)
 	(Spoon1 - object)
 	(DishSponge1 - object)
 	(Lettuce2 - object)
 	(Spatula1 - object)
 	(Knife1 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Ladle1 - object)
 	(Egg1 - object)
 	(Mug1 - object)
 	(Apple1 - object)
 	(Egg2 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Fridge2 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(Bowl1 - receptacle)
 	(Bowl2 - receptacle)
 	(Pot1 - receptacle)
 	(CoffeeMachine1 - receptacle)
 	(Mug1 - receptacle)
 	(GarbageCan2 - receptacle)
 	(Bowl3 - receptacle)
 )
(:init 
 	(sliceable Tomato2)
 	(sliceable Lettuce2)
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Egg1)
 	(sliceable Apple1)
 	(sliceable Egg2)
 	(heatable Tomato2)
 	(heatable Tomato1)
 	(heatable Egg1)
 	(heatable Apple1)
 	(heatable Egg2)
 	(coolable Tomato2)
 	(coolable Lettuce2)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Egg1)
 	(coolable Apple1)
 	(coolable Egg2)
 	(objectAtLocation Lettuce1 Fridge1)
 	(objectAtLocation Ladle1 Plate1)
 	(objectAtLocation Spoon1 SinkBasin1)
 	(objectAtLocation ButterKnife1 Mug1)
 	(objectAtLocation DishSponge1 GarbageCan1)
 	(objectAtLocation Lettuce2 Bowl1)
 	(objectAtLocation Tomato1 Fridge2)
 	(objectAtLocation Tomato2 Bowl2)
 	(objectAtLocation Mug1 CoffeeMachine1)
 	(objectAtLocation Egg1 Bowl3)
 	(objectAtLocation Apple1 GarbageCan2)
 	(objectAtLocation Knife1 CounterTop1)
 	(objectAtLocation Egg2 CounterTop2)
 	(objectAtLocation Spatula1 Pot1)
 )
Output:
(:goal (and
                (isSliced Apple1)
                (isSliced Tomato1)
                (inReceptacle Apple1 Plate1)
                (inReceptacle Tomato1 Plate1)
            )
        )