
########### food_pre2 - 13 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Spoon1 - object)
 	(DishSponge1 - object)
 	(SoapBottle1 - object)
 	(Spatula1 - object)
 	(Bread1 - object)
 	(Lettuce1 - object)
 	(Bowl1 - object)
 	(Potato1 - object)
 	(Apple2 - object)
 	(Apple1 - object)
 	(SaltShaker1 - object)
 	(Potato2 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Cabinet3 - receptacle)
 	(Cabinet1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Cabinet2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(Plate1 - receptacle)
 	(Pot1 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Mug1 - receptacle)
 )
(:init 
 	(sliceable Bread1)
 	(sliceable Lettuce1)
 	(sliceable Potato1)
 	(sliceable Apple2)
 	(sliceable Apple1)
 	(sliceable Potato2)
 	(heatable Bread1)
 	(heatable Potato1)
 	(heatable Apple2)
 	(heatable Apple1)
 	(heatable Potato2)
 	(coolable Bread1)
 	(coolable Lettuce1)
 	(coolable Potato1)
 	(coolable Apple2)
 	(coolable Apple1)
 	(coolable Potato2)
 	(objectAtLocation Apple1 CounterTop1)
 	(objectAtLocation Bowl1 Cabinet1)
 	(objectAtLocation Lettuce1 SinkBasin1)
 	(objectAtLocation Potato1 SinkBasin2)
 	(objectAtLocation Apple2 Pot1)
 	(objectAtLocation Potato2 Fridge1)
 	(objectAtLocation SaltShaker1 Cabinet2)
 	(objectAtLocation Spoon1 Mug1)
 	(objectAtLocation DishSponge1 Bowl1)
 	(objectAtLocation Spatula1 Plate1)
 	(objectAtLocation Bread1 GarbageCan1)
 	(objectAtLocation SoapBottle1 Cabinet3)
 )
Output:
(:goal (and
        (isSliced Apple1)
        (isSliced Apple2)
        (inReceptacle Apple1 Plate1)
        (inReceptacle Apple2 Plate1)
    )
)