
########### food_pre2 - 4 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Lettuce2 - object)
 	(DishSponge1 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Cup1 - object)
 	(Apple2 - object)
 	(Mug1 - object)
 	(Apple1 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Microwave1 - receptacle)
 	(Fridge3 - receptacle)
 	(Fridge2 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(Bowl2 - receptacle)
 	(Cup1 - receptacle)
 	(Plate1 - receptacle)
 )
(:init 
 	(sliceable Lettuce2)
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Apple2)
 	(sliceable Apple1)
 	(heatable Cup1)
 	(heatable Apple2)
 	(heatable Apple1)
 	(heatable Tomato1)
 	(coolable Lettuce2)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Apple2)
 	(coolable Apple1)
 	(objectAtLocation ButterKnife1 Cup1)
 	(objectAtLocation Fork1 Bowl1)
 	(objectAtLocation Mug1 Fridge1)
 	(objectAtLocation Lettuce1 SinkBasin1)
 	(objectAtLocation Lettuce2 Fridge2)
 	(objectAtLocation Cup1 Microwave1)
 	(objectAtLocation DishSponge1 Bowl2)
 	(objectAtLocation Apple1 CounterTop1)
 	(objectAtLocation Apple2 Fridge3)
 	(objectAtLocation Tomato1 CounterTop2)
 )
Output:
(:goal (and
        (isSliced Apple1)
        (isSliced Apple2)
        (inReceptacle Apple1 Plate1)
        (inReceptacle Apple2 Plate1)
    )
)