
########### scene2 - 7 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Spoon1 - object)
 	(Tomato1 - object)
 	(Apple1 - object)
 	(Potato1 - object)
 	(Egg1 - object)
 	(Apple2 - object)
 	(Mug1 - object)
 	(Pan1 - object)
 	(Potato2 - object)
 	(Bowl4 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(Plate1 - receptacle)
 	(Pot1 - receptacle)
 	(Bowl2 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Plate2 - receptacle)
 	(Plate3 - receptacle)
 	(Bowl3 - receptacle)
 	(IceCream1 - object)
 	(Fridge1 - receptacle)
 )
(:init 
 	(sliceable Tomato1)
 	(sliceable Potato1)
 	(sliceable Egg1)
 	(sliceable Apple2)
 	(sliceable Apple1)
 	(sliceable Potato2)
 	(heatable Tomato1)
 	(heatable Potato1)
 	(heatable Egg1)
 	(heatable Apple2)
 	(heatable Apple1)
 	(heatable Potato2)
 	(coolable Tomato1)
 	(coolable Potato1)
 	(coolable Egg1)
 	(coolable Apple2)
 	(coolable Apple1)
 	(coolable Potato2)
 	(objectAtLocation Potato1 SinkBasin1)
 	(objectAtLocation Apple1 Bowl1)
 	(objectAtLocation Pan1 SinkBasin2)
 	(objectAtLocation Tomato1 Plate1)
 	(objectAtLocation Potato2 Plate2)
 	(objectAtLocation Fork1 Pot1)
 	(objectAtLocation Egg1 Bowl2)
 	(objectAtLocation Mug1 Bowl3)
 	(objectAtLocation Spoon1 Bowl4)
 	(objectAtLocation Apple2 Plate3)
 	(objectAtLocation IceCream1 Plate2)
 )
Output:
(:goal (and
            (inReceptacle IceCream1 Fridge1)
        )
)