
########### scene2 - 5 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Spoon1 - object)
 	(DishSponge1 - object)
 	(Potato2 - object)
 	(Bread1 - object)
 	(Potato3 - object)
 	(Pot1 - object)
 	(ButterKnife2 - object)
 	(Potato1 - object)
 	(Apple2 - object)
 	(Apple1 - object)
 	(SaltShaker1 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Cabinet1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Microwave1 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(Bowl2 - receptacle)
 	(SinkBasin3 - receptacle)
 	(Plate1 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Mug1 - receptacle)
 	(Bowl3 - receptacle)
 	(IceCream1 - object)
 	(Fridge1 - receptacle)
 )
(:init 
 	(sliceable Bread1)
 	(sliceable Potato3)
 	(sliceable Potato1)
 	(sliceable Apple2)
 	(sliceable Apple1)
 	(sliceable Potato2)
 	(heatable Bread1)
 	(heatable Potato3)
 	(heatable Potato1)
 	(heatable Apple2)
 	(heatable Apple1)
 	(heatable Potato2)
 	(coolable Bread1)
 	(coolable Potato3)
 	(coolable Potato1)
 	(coolable Apple2)
 	(coolable Apple1)
 	(coolable Potato2)
 	(objectAtLocation ButterKnife1 SinkBasin1)
 	(objectAtLocation Fork1 Mug1)
 	(objectAtLocation Potato1 SinkBasin2)
 	(objectAtLocation Apple1 CounterTop1)
 	(objectAtLocation Spoon1 Bowl1)
 	(objectAtLocation Bread1 Microwave1)
 	(objectAtLocation Potato2 Bowl2)
 	(objectAtLocation Pot1 Cabinet1)
 	(objectAtLocation Potato3 GarbageCan1)
 	(objectAtLocation SaltShaker1 CounterTop2)
 	(objectAtLocation DishSponge1 SinkBasin3)
 	(objectAtLocation ButterKnife2 Plate1)
 	(objectAtLocation Apple2 Bowl3)
 	(objectAtLocation IceCream1 CounterTop1)
 )
Output:
(:goal (and
            (inReceptacle IceCream1 Fridge1)
        )
)