
########### scene2 - 17 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Spoon1 - object)
 	(Knife1 - object)
 	(Bread1 - object)
 	(Tomato1 - object)
 	(Plate1 - object)
 	(Ladle1 - object)
 	(Pot1 - object)
 	(Bowl1 - object)
 	(Potato1 - object)
 	(Bowl2 - object)
 	(Egg1 - object)
 	(Mug1 - object)
 	(Egg2 - object)
 	(Potato2 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(GarbageCan3 - receptacle)
 	(Cabinet1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Microwave1 - receptacle)
 	(Mug2 - receptacle)
 	(Bowl1 - receptacle)
 	(Bowl2 - receptacle)
 	(Plate1 - receptacle)
 	(Microwave3 - receptacle)
 	(Microwave2 - receptacle)
 	(Mug1 - receptacle)
 	(Pan1 - receptacle)
 	(GarbageCan2 - receptacle)
 	(IceCream1 - object)
 )
(:init 
 	(sliceable Bread1)
 	(sliceable Tomato1)
 	(sliceable Potato1)
 	(sliceable Egg1)
 	(sliceable Egg2)
 	(sliceable Potato2)
 	(heatable Bread1)
 	(heatable Tomato1)
 	(heatable Potato1)
 	(heatable Egg1)
 	(heatable Egg2)
 	(heatable Potato2)
 	(coolable Bread1)
 	(coolable Tomato1)
 	(coolable Potato1)
 	(coolable Egg1)
 	(coolable Egg2)
 	(coolable Potato2)
 	(objectAtLocation Mug1 Bowl1)
 	(objectAtLocation Egg1 Pan1)
 	(objectAtLocation Fork1 Mug1)
 	(objectAtLocation Pot1 CounterTop1)
 	(objectAtLocation Potato1 GarbageCan1)
 	(objectAtLocation Ladle1 Bowl2)
 	(objectAtLocation Bread1 GarbageCan2)
 	(objectAtLocation Tomato1 Fridge1)
 	(objectAtLocation Plate1 Microwave1)
 	(objectAtLocation Bowl1 Cabinet1)
 	(objectAtLocation Spoon1 Mug2)
 	(objectAtLocation Bowl2 Microwave2)
 	(objectAtLocation Knife1 Plate1)
 	(objectAtLocation Potato2 Microwave3)
 	(objectAtLocation Egg2 GarbageCan3)
 	(objectAtLocation IceCream1 Microwave2)
 )
Output:
(:goal (and
            (inReceptacle IceCream1 Fridge1)
        )
)