
########### scene2 - 15 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Spoon1 - object)
 	(Cup1 - object)
 	(SoapBottle1 - object)
 	(Pot1 - object)
 	(ButterKnife2 - object)
 	(Fork2 - object)
 	(Apple2 - object)
 	(Apple1 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Pan2 - receptacle)
 	(Cabinet1 - receptacle)
 	(Bowl2 - receptacle)
 	(Bowl1 - receptacle)
 	(Cup1 - receptacle)
 	(Mug1 - receptacle)
 	(Pan1 - receptacle)
 	(Bowl3 - receptacle)
 	(IceCream1 - object)
 )
(:init 
 	(sliceable Apple2)
 	(sliceable Apple1)
 	(heatable Cup1)
 	(heatable Apple2)
 	(heatable Apple1)
 	(coolable Apple2)
 	(coolable Apple1)
 	(objectAtLocation ButterKnife1 Bowl1)
 	(objectAtLocation Apple1 Bowl2)
 	(objectAtLocation Fork1 Pan1)
 	(objectAtLocation Pot1 Fridge1)
 	(objectAtLocation Apple2 Pan2)
 	(objectAtLocation ButterKnife2 Cup1)
 	(objectAtLocation Fork2 Bowl3)
 	(objectAtLocation Spoon1 Mug1)
 	(objectAtLocation Cup1 CounterTop1)
 	(objectAtLocation SoapBottle1 Cabinet1)
 	(objectAtLocation IceCream1 Pan2)
 )
Output:
(:goal (and
            (inReceptacle IceCream1 Fridge1)
        )
)