
########### scene2 - 1 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Tomato2 - object)
 	(Mug2 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Bowl1 - object)
 	(Ladle1 - object)
 	(Bowl2 - object)
 	(Egg1 - object)
 	(Mug1 - object)
 	(Apple1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Microwave1 - receptacle)
 	(Fridge2 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(Bowl1 - receptacle)
 	(Microwave2 - receptacle)
 	(SinkBasin2 - receptacle)
 	(IceCream1 - object)
 )
(:init 
 	(sliceable Tomato2)
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Egg1)
 	(sliceable Apple1)
 	(heatable Tomato2)
 	(heatable Egg1)
 	(heatable Tomato1)
 	(heatable Apple1)
 	(coolable Tomato2)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Egg1)
 	(coolable Apple1)
 	(objectAtLocation Lettuce1 Fridge1)
 	(objectAtLocation Apple1 Fridge2)
 	(objectAtLocation Tomato1 CounterTop1)
 	(objectAtLocation Tomato2 Plate1)
 	(objectAtLocation Mug1 Bowl1)
 	(objectAtLocation Bowl1 CounterTop2)
 	(objectAtLocation Ladle1 SinkBasin1)
 	(objectAtLocation Egg1 Microwave1)
 	(objectAtLocation Bowl2 SinkBasin2)
 	(objectAtLocation Mug2 Microwave2)
 	(objectAtLocation IceCream1 Plate1)
 )
Output:
(:goal (and
            (inReceptacle IceCream1 Fridge1)
        )
)