
########### scene2 - 12 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Tomato2 - object)
 	(SoapBottle1 - object)
 	(DishSponge1 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Apple3 - object)
 	(Potato1 - object)
 	(Cup1 - object)
 	(Apple2 - object)
 	(Mug1 - object)
 	(Apple1 - object)
 	(SaltShaker1 - object)
 	(CounterTop1 - receptacle)
 	(Cabinet3 - receptacle)
 	(Cabinet1 - receptacle)
 	(Microwave1 - receptacle)
 	(CounterTop2 - receptacle)
 	(Cabinet2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(Pot1 - receptacle)
 	(Microwave2 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Pan1 - receptacle)
 	(IceCream1 - object)
 	(Fridge1 - receptacle)
 )
(:init 
 	(sliceable Tomato2)
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Apple3)
 	(sliceable Potato1)
 	(sliceable Apple2)
 	(sliceable Apple1)
 	(heatable Tomato2)
 	(heatable Tomato1)
 	(heatable Apple3)
 	(heatable Potato1)
 	(heatable Cup1)
 	(heatable Apple2)
 	(heatable Apple1)
 	(coolable Tomato2)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Apple3)
 	(coolable Potato1)
 	(coolable Apple2)
 	(coolable Apple1)
 	(objectAtLocation Apple1 SinkBasin1)
 	(objectAtLocation DishSponge1 Cabinet1)
 	(objectAtLocation Apple2 Microwave1)
 	(objectAtLocation Apple3 Pan1)
 	(objectAtLocation Potato1 Microwave2)
 	(objectAtLocation SaltShaker1 Cabinet2)
 	(objectAtLocation Mug1 CounterTop1)
 	(objectAtLocation Lettuce1 SinkBasin2)
 	(objectAtLocation Cup1 CounterTop2)
 	(objectAtLocation SoapBottle1 Cabinet3)
 	(objectAtLocation Tomato1 Pot1)
 	(objectAtLocation Tomato2 Plate1)
 	(objectAtLocation IceCream1 Plate1)
 )
Output:
(:goal (and
            (inReceptacle IceCream1 Fridge1)
        )
)