
########### scene2 - 19 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Lettuce2 - object)
 	(DishSponge1 - object)
 	(Spatula2 - object)
 	(Spatula1 - object)
 	(Knife1 - object)
 	(Bread1 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Ladle1 - object)
 	(Fork2 - object)
 	(Egg1 - object)
 	(Cup1 - object)
 	(Apple1 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Pan2 - receptacle)
 	(Mug1 - receptacle)
 	(CounterTop3 - receptacle)
 	(Microwave1 - receptacle)
 	(Pot3 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(Bowl1 - receptacle)
 	(Pot1 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Pot2 - receptacle)
 	(Pan1 - receptacle)
 	(IceCream1 - object)
 )
(:init 
 	(sliceable Lettuce2)
 	(sliceable Bread1)
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Egg1)
 	(sliceable Apple1)
 	(heatable Bread1)
 	(heatable Tomato1)
 	(heatable Egg1)
 	(heatable Cup1)
 	(heatable Apple1)
 	(coolable Lettuce2)
 	(coolable Bread1)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Egg1)
 	(coolable Apple1)
 	(objectAtLocation Apple1 CounterTop1)
 	(objectAtLocation Spatula1 Pan1)
 	(objectAtLocation Egg1 Pot1)
 	(objectAtLocation Ladle1 CounterTop2)
 	(objectAtLocation Cup1 Microwave1)
 	(objectAtLocation Fork1 Pot2)
 	(objectAtLocation Fork2 Plate1)
 	(objectAtLocation Spatula2 Pot3)
 	(objectAtLocation DishSponge1 Pan2)
 	(objectAtLocation Lettuce1 Fridge1)
 	(objectAtLocation ButterKnife1 Mug1)
 	(objectAtLocation Lettuce2 SinkBasin1)
 	(objectAtLocation Tomato1 Bowl1)
 	(objectAtLocation Bread1 CounterTop3)
 	(objectAtLocation Knife1 SinkBasin2)
 	(objectAtLocation IceCream1 CounterTop1)
 )
Output:
(:goal (and
            (inReceptacle IceCream1 Fridge1)
        )
)