
########### scene2 - 14 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Lettuce2 - object)
 	(SoapBottle1 - object)
 	(DishSponge1 - object)
 	(Spatula1 - object)
 	(Ladle2 - object)
 	(Bread1 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Bread2 - object)
 	(Ladle1 - object)
 	(Potato1 - object)
 	(Lettuce3 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Cabinet1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Fridge2 - receptacle)
 	(CounterTop2 - receptacle)
 	(Cabinet2 - receptacle)
 	(Plate1 - receptacle)
 	(Bowl1 - receptacle)
 	(Pot1 - receptacle)
 	(Pot2 - receptacle)
 	(GarbageCan2 - receptacle)
 	(IceCream1 - object)
 )
(:init 
 	(sliceable Lettuce2)
 	(sliceable Bread1)
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Bread2)
 	(sliceable Potato1)
 	(sliceable Lettuce3)
 	(heatable Potato1)
 	(heatable Bread1)
 	(heatable Tomato1)
 	(heatable Bread2)
 	(coolable Lettuce2)
 	(coolable Bread1)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Bread2)
 	(coolable Potato1)
 	(coolable Lettuce3)
 	(objectAtLocation Ladle1 Pot1)
 	(objectAtLocation Tomato1 GarbageCan1)
 	(objectAtLocation Bread1 CounterTop1)
 	(objectAtLocation Bread2 Fridge1)
 	(objectAtLocation Spatula1 Plate1)
 	(objectAtLocation Lettuce1 Bowl1)
 	(objectAtLocation Lettuce2 Fridge2)
 	(objectAtLocation SoapBottle1 CounterTop2)
 	(objectAtLocation DishSponge1 Cabinet1)
 	(objectAtLocation Ladle2 Cabinet2)
 	(objectAtLocation Lettuce3 GarbageCan2)
 	(objectAtLocation Potato1 Pot2)
 	(objectAtLocation IceCream1 Cabinet1)
 )
Output:
(:goal (and
            (inReceptacle IceCream1 Fridge2)
        )
)