
########### scene2 - 6 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Tomato2 - object)
 	(Spatula2 - object)
 	(Spatula1 - object)
 	(Knife1 - object)
 	(Bread1 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Ladle1 - object)
 	(Pot1 - object)
 	(Potato1 - object)
 	(Egg1 - object)
 	(Apple2 - object)
 	(Apple1 - object)
 	(ButterKnife1 - object)
 	(Fridge1 - receptacle)
 	(GarbageCan3 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Bowl4 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl2 - receptacle)
 	(Bowl1 - receptacle)
 	(Pot1 - receptacle)
 	(SinkBasin3 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Mug1 - receptacle)
 	(Pan1 - receptacle)
 	(GarbageCan2 - receptacle)
 	(Bowl3 - receptacle)
 	(IceCream1 - object)
 )
(:init 
 	(sliceable Tomato2)
 	(sliceable Bread1)
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Potato1)
 	(sliceable Egg1)
 	(sliceable Apple2)
 	(sliceable Apple1)
 	(heatable Tomato2)
 	(heatable Bread1)
 	(heatable Tomato1)
 	(heatable Potato1)
 	(heatable Egg1)
 	(heatable Apple2)
 	(heatable Apple1)
 	(coolable Tomato2)
 	(coolable Bread1)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Potato1)
 	(coolable Egg1)
 	(coolable Apple2)
 	(coolable Apple1)
 	(objectAtLocation Lettuce1 Bowl1)
 	(objectAtLocation Egg1 Pan1)
 	(objectAtLocation Apple1 Bowl2)
 	(objectAtLocation ButterKnife1 Mug1)
 	(objectAtLocation Knife1 Pot1)
 	(objectAtLocation Tomato1 GarbageCan1)
 	(objectAtLocation Ladle1 SinkBasin1)
 	(objectAtLocation Bread1 GarbageCan2)
 	(objectAtLocation Spatula1 Bowl3)
 	(objectAtLocation Pot1 SinkBasin2)
 	(objectAtLocation Spatula2 SinkBasin3)
 	(objectAtLocation Potato1 Fridge1)
 	(objectAtLocation Apple2 GarbageCan3)
 	(objectAtLocation Tomato2 Bowl4)
 	(objectAtLocation IceCream1 GarbageCan3)
 )
Output:
(:goal (and
            (inReceptacle IceCream1 Fridge1)
        )
)