
########### scene2 - 2 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Pot2 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(ButterKnife3 - object)
 	(Bowl1 - object)
 	(Ladle1 - object)
 	(ButterKnife2 - object)
 	(Pot1 - object)
 	(Potato1 - object)
 	(Egg1 - object)
 	(Cup1 - object)
 	(Mug1 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Pan2 - receptacle)
 	(Cabinet1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Microwave1 - receptacle)
 	(Cabinet2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(Bowl2 - receptacle)
 	(Microwave2 - receptacle)
 	(Mug1 - receptacle)
 	(Pan1 - receptacle)
 	(Bowl3 - receptacle)
 	(IceCream1 - object)
 )
(:init 
 	(sliceable Egg1)
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Potato1)
 	(heatable Egg1)
 	(heatable Cup1)
 	(heatable Tomato1)
 	(heatable Potato1)
 	(coolable Egg1)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Potato1)
 	(objectAtLocation Pot1 CounterTop1)
 	(objectAtLocation Mug1 Microwave1)
 	(objectAtLocation ButterKnife1 Bowl1)
 	(objectAtLocation Cup1 Cabinet1)
 	(objectAtLocation ButterKnife2 Mug1)
 	(objectAtLocation Egg1 Microwave2)
 	(objectAtLocation Potato1 Bowl2)
 	(objectAtLocation Ladle1 Cabinet2)
 	(objectAtLocation Lettuce1 GarbageCan1)
 	(objectAtLocation Fork1 Pan1)
 	(objectAtLocation Bowl1 Fridge1)
 	(objectAtLocation ButterKnife3 Pan2)
 	(objectAtLocation Tomato1 Bowl3)
 	(objectAtLocation Pot2 SinkBasin1)
 	(objectAtLocation IceCream1 SinkBasin1)
 )
Output:
(:goal (and
            (inReceptacle IceCream1 Fridge1)
        )
)