
########### scene2 - 3 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(SoapBottle1 - object)
 	(Lettuce2 - object)
 	(Knife1 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Bowl1 - object)
 	(Ladle1 - object)
 	(Pot1 - object)
 	(Egg1 - object)
 	(Apple1 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Pan2 - receptacle)
 	(Cabinet1 - receptacle)
 	(StoveBurner1 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(Plate1 - receptacle)
 	(Pot1 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Pot2 - receptacle)
 	(Pan1 - receptacle)
 	(IceCream1 - object)
 )
(:init 
 	(sliceable Lettuce2)
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Egg1)
 	(sliceable Apple1)
 	(heatable Egg1)
 	(heatable Tomato1)
 	(heatable Apple1)
 	(coolable Lettuce2)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Egg1)
 	(coolable Apple1)
 	(objectAtLocation Tomato1 Pan1)
 	(objectAtLocation Pot1 StoveBurner1)
 	(objectAtLocation Lettuce1 Bowl1)
 	(objectAtLocation SoapBottle1 Cabinet1)
 	(objectAtLocation Ladle1 Pot1)
 	(objectAtLocation Lettuce2 SinkBasin1)
 	(objectAtLocation Knife1 CounterTop1)
 	(objectAtLocation ButterKnife1 Plate1)
 	(objectAtLocation Apple1 Pot2)
 	(objectAtLocation Bowl1 Fridge1)
 	(objectAtLocation Fork1 Pan2)
 	(objectAtLocation Egg1 SinkBasin2)
 	(objectAtLocation IceCream1 Plate1)
 )
Output:
(:goal (and
            (inReceptacle IceCream1 Fridge1)
        )
)