
########### scene2 - 18 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Spatula1 - object)
 	(Knife1 - object)
 	(Bread1 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Plate1 - object)
 	(Cup1 - object)
 	(Apple2 - object)
 	(Apple1 - object)
 	(CounterTop1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(CounterTop3 - receptacle)
 	(Microwave1 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(Pot1 - receptacle)
 	(Microwave2 - receptacle)
 	(Pan1 - receptacle)
 	(IceCream1 - object)
 	(Fridge1 - receptacle)
 )
(:init 
 	(sliceable Bread1)
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Apple2)
 	(sliceable Apple1)
 	(heatable Bread1)
 	(heatable Tomato1)
 	(heatable Cup1)
 	(heatable Apple2)
 	(heatable Apple1)
 	(coolable Bread1)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Apple2)
 	(coolable Apple1)
 	(objectAtLocation Bread1 CounterTop1)
 	(objectAtLocation Fork1 Pot1)
 	(objectAtLocation Plate1 CounterTop2)
 	(objectAtLocation Tomato1 GarbageCan1)
 	(objectAtLocation Cup1 Microwave1)
 	(objectAtLocation Spatula1 CounterTop3)
 	(objectAtLocation Knife1 Pan1)
 	(objectAtLocation Lettuce1 Plate1)
 	(objectAtLocation Apple1 Microwave2)
 	(objectAtLocation Apple2 SinkBasin1)
 	(objectAtLocation IceCream1 Plate1)
 )
Output:
(:goal (and
            (inReceptacle IceCream1 Fridge1)
        )
)