
########### scene6 - 6 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Spoon1 - object)
 	(Knife1 - object)
 	(Mug2 - object)
 	(Tomato1 - object)
 	(Apple1 - object)
 	(Ladle1 - object)
 	(ButterKnife2 - object)
 	(Mug1 - object)
 	(Pan1 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Fridge2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(Bowl1 - receptacle)
 	(Pot1 - receptacle)
 	(Bowl2 - receptacle)
 	(Pan1 - receptacle)
 	(Oven1 - receptacle)
 	(Microwave1 - receptacle)
 	(Floor1 - receptacle)
 )
(:init 
 	(sliceable Tomato1)
 	(sliceable Apple1)
 	(heatable Tomato1)
 	(heatable Apple1)
 	(coolable Tomato1)
 	(coolable Apple1)
 	(objectAtLocation Knife1 Floor1)
 	(objectAtLocation Mug1 Fridge1)
 	(objectAtLocation Spoon1 Pot1)
 	(objectAtLocation ButterKnife1 SinkBasin1)
 	(objectAtLocation Pan1 Fridge2)
 	(objectAtLocation Mug2 Plate1)
 	(objectAtLocation Ladle1 Pan1)
 	(objectAtLocation ButterKnife2 Bowl1)
 	(objectAtLocation Tomato1 CounterTop1)
 	(objectAtLocation Apple1 GarbageCan1)
 )
Output:
(:goal (and
                (objectAtLocation Knife1 Cabinet1)
                (objectAtLocation Mug1 Cabinet1)
                (objectAtLocation Spoon1 Cabinet1)
                (objectAtLocation ButterKnife1 Cabinet1)
                (objectAtLocation Pan1 Cabinet1)
                (objectAtLocation Mug2 Cabinet1)
                (objectAtLocation Ladle1 Cabinet1)
                (objectAtLocation ButterKnife2 Cabinet1)
                (objectAtLocation Tomato1 Fridge1)
                (objectAtLocation Apple1 Fridge1)
            )
        )