
########### scene6 - 15 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Lettuce2 - object)
 	(DishSponge1 - object)
 	(SoapBottle1 - object)
 	(PepperShaker1 - object)
 	(Ladle2 - object)
 	(Lettuce1 - object)
 	(Ladle1 - object)
 	(Pot1 - object)
 	(Potato1 - object)
 	(Egg1 - object)
 	(Apple1 - object)
 	(Lettuce3 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Cabinet1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(CounterTop3 - receptacle)
 	(StoveBurner1 - receptacle)
 	(Fridge3 - receptacle)
 	(Fridge2 - receptacle)
 	(CounterTop2 - receptacle)
 	(Plate1 - receptacle)
 	(Pot1 - receptacle)
 	(GarbageCan2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Oven1 - receptacle)
 	(Microwave1 - receptacle)
 	(Floor1 - receptacle)
 )
(:init 
 	(sliceable Lettuce2)
 	(sliceable Lettuce1)
 	(sliceable Potato1)
 	(sliceable Egg1)
 	(sliceable Apple1)
 	(sliceable Lettuce3)
 	(heatable Egg1)
 	(heatable Apple1)
 	(heatable Potato1)
 	(coolable Lettuce2)
 	(coolable Lettuce1)
 	(coolable Potato1)
 	(coolable Egg1)
 	(coolable Apple1)
 	(coolable Lettuce3)
 	(objectAtLocation Egg1 Floor1)
 	(objectAtLocation Lettuce1 GarbageCan1)
 	(objectAtLocation Ladle1 Cabinet1)
 	(objectAtLocation DishSponge1 Plate1)
 	(objectAtLocation Apple1 GarbageCan2)
 	(objectAtLocation Lettuce2 Fridge1)
 	(objectAtLocation Lettuce3 Pot1)
 	(objectAtLocation SoapBottle1 CounterTop1)
 	(objectAtLocation Potato1 Fridge2)
 	(objectAtLocation PepperShaker1 CounterTop2)
 	(objectAtLocation Ladle2 CounterTop3)
 	(objectAtLocation Pot1 StoveBurner1)
 )
Output:
(:goal (and
                (objectAtLocation Egg1 Cabinet1)
                (objectAtLocation Lettuce1 Fridge1)
                (objectAtLocation Ladle1 Cabinet1)
                (objectAtLocation DishSponge1 Plate1)
                (objectAtLocation Apple1 Fridge1)
                (objectAtLocation Lettuce2 Fridge1)
                (objectAtLocation Lettuce3 Fridge1)
                (objectAtLocation SoapBottle1 CounterTop1)
                (objectAtLocation Potato1 Fridge1)
                (objectAtLocation PepperShaker1 Cabinet1)
                (objectAtLocation Ladle2 Cabinet1)
                (objectAtLocation Pot1 Cabinet1)
            )
        )