
########### scene6 - 18 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Pan2 - object)
 	(Knife1 - object)
 	(Lettuce1 - object)
 	(Bowl2 - object)
 	(Bowl1 - object)
 	(Ladle1 - object)
 	(Pan1 - object)
 	(Cup1 - object)
 	(Apple1 - object)
 	(SaltShaker1 - object)
 	(Bowl3 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Cabinet3 - receptacle)
 	(Cabinet1 - receptacle)
 	(Microwave1 - receptacle)
 	(Fridge2 - receptacle)
 	(CounterTop2 - receptacle)
 	(Cabinet2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Pot1 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Pot2 - receptacle)
 	(Oven1 - receptacle)
 	(Floor1 - receptacle)
 )
(:init 
 	(sliceable Lettuce1)
 	(sliceable Apple1)
 	(heatable Cup1)
 	(heatable Apple1)
 	(coolable Lettuce1)
 	(coolable Apple1)
 	(objectAtLocation Bowl3 Floor1)
 	(objectAtLocation Bowl1 SinkBasin1)
 	(objectAtLocation Apple1 Microwave1)
 	(objectAtLocation Bowl2 Fridge1)
 	(objectAtLocation Lettuce1 Pot1)
 	(objectAtLocation Ladle1 Cabinet2)
 	(objectAtLocation Fork1 Pot2)
 	(objectAtLocation Knife1 SinkBasin2)
 	(objectAtLocation SaltShaker1 Cabinet3)
 	(objectAtLocation Cup1 CounterTop1)
 	(objectAtLocation Pan1 CounterTop2)
 	(objectAtLocation Pan2 Fridge2)
 )
Output:
(:goal (and
                (objectAtLocation Bowl3 Cabinet1)
                (objectAtLocation Bowl1 Cabinet1)
                (objectAtLocation Apple1 Fridge1)
                (objectAtLocation Bowl2 Cabinet1)
                (objectAtLocation Lettuce1 Fridge1)
                (objectAtLocation Ladle1 Cabinet1)
                (objectAtLocation Fork1 Cabinet1)
                (objectAtLocation Knife1 Cabinet1)
                (objectAtLocation SaltShaker1 Cabinet1)
                (objectAtLocation Cup1 Cabinet1)
                (objectAtLocation Pan1 Cabinet1)
                (objectAtLocation Pan2 Cabinet1)
            )
        )