
########### scene6 - 7 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Spoon1 - object)
 	(DishSponge1 - object)
 	(Spatula1 - object)
 	(PepperShaker1 - object)
 	(Lettuce1 - object)
 	(Apple1 - object)
 	(ButterKnife2 - object)
 	(Egg1 - object)
 	(Fork2 - object)
 	(Apple2 - object)
 	(Pan1 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Pan2 - receptacle)
 	(CounterTop3 - receptacle)
 	(Microwave1 - receptacle)
 	(SinkBasin4 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(SinkBasin3 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Cup1 - receptacle)
 	(Pan1 - receptacle)
 	(Oven1 - receptacle)
 	(Floor1 - receptacle)
 )
(:init 
 	(sliceable Egg1)
 	(sliceable Apple2)
 	(sliceable Lettuce1)
 	(sliceable Apple1)
 	(heatable Egg1)
 	(heatable Cup1)
 	(heatable Apple2)
 	(heatable Apple1)
 	(coolable Egg1)
 	(coolable Apple2)
 	(coolable Lettuce1)
 	(coolable Apple1)
 	(objectAtLocation Apple1 Floor1)
 	(objectAtLocation Spoon1 CounterTop1)
 	(objectAtLocation Egg1 Microwave1)
 	(objectAtLocation DishSponge1 Bowl1)
 	(objectAtLocation Pan1 Fridge1)
 	(objectAtLocation Lettuce1 SinkBasin1)
 	(objectAtLocation Fork1 Cup1)
 	(objectAtLocation ButterKnife1 CounterTop2)
 	(objectAtLocation ButterKnife2 SinkBasin2)
 	(objectAtLocation Spatula1 SinkBasin3)
 	(objectAtLocation Apple2 SinkBasin4)
 	(objectAtLocation PepperShaker1 CounterTop3)
 	(objectAtLocation Fork2 Pan2)
 )
Output:
(:goal (and
                (objectAtLocation Apple1 Fridge1)
                (objectAtLocation Spoon1 Cabinet1)
                (objectAtLocation Egg1 Fridge1)
                (objectAtLocation DishSponge1 SinkBasin1)
                (objectAtLocation Pan1 CounterTop1)
                (objectAtLocation Lettuce1 Fridge1)
                (objectAtLocation Fork1 Cabinet1)
                (objectAtLocation ButterKnife1 Cabinet1)
                (objectAtLocation ButterKnife2 Cabinet1)
                (objectAtLocation Spatula1 Cabinet1)
                (objectAtLocation Apple2 Fridge1)
                (objectAtLocation PepperShaker1 Cabinet1)
                (objectAtLocation Fork2 Cabinet1)
            )
        )