
########### scene6 - 10 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Lettuce2 - object)
 	(Spoon1 - object)
 	(Knife1 - object)
 	(Ladle2 - object)
 	(Mug2 - object)
 	(Lettuce1 - object)
 	(Knife2 - object)
 	(Bowl1 - object)
 	(Ladle1 - object)
 	(Potato1 - object)
 	(Egg1 - object)
 	(Cup1 - object)
 	(Mug1 - object)
 	(Egg2 - object)
 	(Potato2 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Plate2 - receptacle)
 	(Microwave1 - receptacle)
 	(SinkBasin4 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(SinkBasin3 - receptacle)
 	(Pot1 - receptacle)
 	(Bowl1 - receptacle)
 	(Bowl2 - receptacle)
 	(Microwave2 - receptacle)
 	(SinkBasin2 - receptacle)
 	(SinkBasin5 - receptacle)
 	(Oven1 - receptacle)
 	(Floor1 - receptacle)
 )
(:init 
 	(sliceable Lettuce2)
 	(sliceable Lettuce1)
 	(sliceable Potato1)
 	(sliceable Egg1)
 	(sliceable Egg2)
 	(sliceable Potato2)
 	(heatable Potato1)
 	(heatable Egg1)
 	(heatable Cup1)
 	(heatable Egg2)
 	(heatable Potato2)
 	(coolable Lettuce2)
 	(coolable Lettuce1)
 	(coolable Potato1)
 	(coolable Egg1)
 	(coolable Egg2)
 	(coolable Potato2)
 	(objectAtLocation Ladle2 Floor1)
 	(objectAtLocation Lettuce1 SinkBasin1)
 	(objectAtLocation Ladle1 SinkBasin2)
 	(objectAtLocation Potato1 Microwave1)
 	(objectAtLocation Lettuce2 GarbageCan1)
 	(objectAtLocation Knife1 Plate1)
 	(objectAtLocation Cup1 SinkBasin3)
 	(objectAtLocation Egg1 Pot1)
 	(objectAtLocation Mug1 Bowl1)
 	(objectAtLocation Potato2 Fridge1)
 	(objectAtLocation Mug2 Plate2)
 	(objectAtLocation Egg2 Microwave2)
 	(objectAtLocation Spoon1 SinkBasin4)
 	(objectAtLocation Knife2 Bowl2)
 	(objectAtLocation Bowl1 SinkBasin5)
 )
Output:
(:goal (and
                (objectAtLocation Ladle2 Cabinet1)
                (objectAtLocation Lettuce1 Fridge1)
                (objectAtLocation Ladle1 Cabinet1)
                (objectAtLocation Potato1 Fridge1)
                (objectAtLocation Lettuce2 Fridge1)
                (objectAtLocation Knife1 Cabinet1)
                (objectAtLocation Cup1 Cabinet1)
                (objectAtLocation Egg1 Fridge1)
                (objectAtLocation Mug1 Cabinet1)
                (objectAtLocation Potato2 Fridge1)
                (objectAtLocation Mug2 Cabinet1)
                (objectAtLocation Egg2 Fridge1)
                (objectAtLocation Spoon1 Cabinet1)
                (objectAtLocation Knife2 Cabinet1)
                (objectAtLocation Bowl1 Cabinet1)
            )
        )