
########### scene6 - 4 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Spoon1 - object)
 	(Knife1 - object)
 	(Knife3 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Knife2 - object)
 	(Plate1 - object)
 	(Ladle1 - object)
 	(Pot1 - object)
 	(Plate2 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Plate2 - receptacle)
 	(SinkBasin4 - receptacle)
 	(Fridge2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(SinkBasin3 - receptacle)
 	(Pot1 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Pan1 - receptacle)
 	(Oven1 - receptacle)
 	(Microwave1 - receptacle)
 	(Floor1 - receptacle)
 )
(:init 
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(heatable Tomato1)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(objectAtLocation Spoon1 Floor1)
 	(objectAtLocation Tomato1 GarbageCan1)
 	(objectAtLocation Plate1 CounterTop1)
 	(objectAtLocation Knife1 SinkBasin1)
 	(objectAtLocation Lettuce1 Fridge1)
 	(objectAtLocation Pot1 SinkBasin2)
 	(objectAtLocation ButterKnife1 SinkBasin3)
 	(objectAtLocation Plate2 Fridge2)
 	(objectAtLocation Ladle1 Pan1)
 	(objectAtLocation Fork1 SinkBasin4)
 	(objectAtLocation Knife2 Plate1)
 	(objectAtLocation Knife3 Pot1)
 )
Output:
(:goal (and
                (objectAtLocation Spoon1 Cabinet1)
                (objectAtLocation Tomato1 Fridge1)
                (objectAtLocation Plate1 Cabinet1)
                (objectAtLocation Knife1 Cabinet1)
                (objectAtLocation Lettuce1 Fridge1)
                (objectAtLocation Pot1 Cabinet1)
                (objectAtLocation ButterKnife1 Cabinet1)
                (objectAtLocation Plate2 Cabinet1)
                (objectAtLocation Ladle1 Cabinet1)
                (objectAtLocation Fork1 Cabinet1)
                (objectAtLocation Knife2 Cabinet1)
                (objectAtLocation Knife3 Cabinet1)
            )
        )