
########### scene6 - 3 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Spoon1 - object)
 	(Spoon2 - object)
 	(Plate1 - object)
 	(ButterKnife2 - object)
 	(Pot1 - object)
 	(Egg1 - object)
 	(Fork2 - object)
 	(Pan1 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Cabinet1 - receptacle)
 	(Microwave1 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Cup1 - receptacle)
 	(Mug1 - receptacle)
 	(Oven1 - receptacle)
 	(Floor1 - receptacle)
 )
(:init 
 	(sliceable Egg1)
 	(heatable Egg1)
 	(heatable Cup1)
 	(coolable Egg1)
 	(objectAtLocation ButterKnife1 Floor1)
 	(objectAtLocation Spoon1 Bowl1)
 	(objectAtLocation Pan1 Cabinet1)
 	(objectAtLocation Egg1 SinkBasin2)
 	(objectAtLocation Spoon2 Mug1)
 	(objectAtLocation ButterKnife2 CounterTop1)
 	(objectAtLocation Plate1 Microwave1)
 	(objectAtLocation Pot1 Fridge1)
 	(objectAtLocation Fork1 CounterTop2)
 	(objectAtLocation Fork2 Cup1)
 )
Output:
(:goal (and
                (objectAtLocation ButterKnife1 Cabinet1)
                (objectAtLocation Spoon1 Cabinet1)
                (objectAtLocation Pan1 Cabinet1)
                (objectAtLocation Egg1 Fridge1)
                (objectAtLocation Spoon2 Cabinet1)
                (objectAtLocation ButterKnife2 Cabinet1)
                (objectAtLocation Plate1 Cabinet1)
                (objectAtLocation Pot1 Cabinet1)
                (objectAtLocation Fork1 Cabinet1)
                (objectAtLocation Fork2 Cabinet1)
            )
        )