
########### scene6 - 20 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Spoon1 - object)
 	(Knife1 - object)
 	(PepperShaker1 - object)
 	(Plate2 - object)
 	(Bread1 - object)
 	(Lettuce1 - object)
 	(Apple1 - object)
 	(Plate1 - object)
 	(ButterKnife2 - object)
 	(Potato1 - object)
 	(Egg1 - object)
 	(Apple2 - object)
 	(Pan1 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(CounterTop3 - receptacle)
 	(CounterTop4 - receptacle)
 	(Microwave1 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(Bowl1 - receptacle)
 	(SinkBasin3 - receptacle)
 	(Microwave2 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Pan1 - receptacle)
 	(GarbageCan2 - receptacle)
 	(Oven1 - receptacle)
 	(Floor1 - receptacle)
 )
(:init 
 	(sliceable Bread1)
 	(sliceable Lettuce1)
 	(sliceable Potato1)
 	(sliceable Egg1)
 	(sliceable Apple2)
 	(sliceable Apple1)
 	(heatable Bread1)
 	(heatable Potato1)
 	(heatable Egg1)
 	(heatable Apple2)
 	(heatable Apple1)
 	(coolable Bread1)
 	(coolable Lettuce1)
 	(coolable Potato1)
 	(coolable Egg1)
 	(coolable Apple2)
 	(coolable Apple1)
 	(objectAtLocation ButterKnife1 Floor1)
 	(objectAtLocation Knife1 CounterTop1)
 	(objectAtLocation Bread1 GarbageCan1)
 	(objectAtLocation Pan1 CounterTop2)
 	(objectAtLocation Potato1 SinkBasin1)
 	(objectAtLocation Plate1 CounterTop3)
 	(objectAtLocation Spoon1 Plate1)
 	(objectAtLocation Apple1 Bowl1)
 	(objectAtLocation Egg1 Fridge1)
 	(objectAtLocation Fork1 SinkBasin2)
 	(objectAtLocation Apple2 Microwave1)
 	(objectAtLocation PepperShaker1 CounterTop4)
 	(objectAtLocation Lettuce1 GarbageCan2)
 	(objectAtLocation ButterKnife2 Pan1)
 	(objectAtLocation Plate2 Microwave2)
 )
Output:
(:goal (and
        (objectAtLocation Fork1 Cabinet1)
        (objectAtLocation Spoon1 Cabinet1)
        (objectAtLocation Knife1 Cabinet1)
        (objectAtLocation PepperShaker1 Cabinet1)
        (objectAtLocation Plate2 Cabinet1)
        (objectAtLocation Bread1 Cabinet1)
        (objectAtLocation Lettuce1 Fridge1)
        (objectAtLocation Apple1 Fridge1)
        (objectAtLocation Plate1 Cabinet1)
        (objectAtLocation ButterKnife2 Cabinet1)
        (objectAtLocation Potato1 Fridge1)
        (objectAtLocation Egg1 Fridge1)
        (objectAtLocation Apple2 Fridge1)
        (objectAtLocation Pan1 Cabinet1)
        (objectAtLocation ButterKnife1 Cabinet1)
    )
)