
########### scene6 - 16 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Spoon1 - object)
 	(DishSponge1 - object)
 	(Cup1 - object)
 	(Spatula1 - object)
 	(Fork3 - object)
 	(Knife1 - object)
 	(SoapBottle1 - object)
 	(Lettuce1 - object)
 	(Potato1 - object)
 	(Egg1 - object)
 	(Fork2 - object)
 	(Apple1 - object)
 	(Potato2 - object)
 	(CounterTop1 - receptacle)
 	(Plate4 - receptacle)
 	(Cabinet1 - receptacle)
 	(Mug1 - receptacle)
 	(Plate3 - receptacle)
 	(CounterTop2 - receptacle)
 	(Cabinet2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(Bowl1 - receptacle)
 	(Pot1 - receptacle)
 	(Plate2 - receptacle)
 	(Pot2 - receptacle)
 	(Pan1 - receptacle)
 	(Oven1 - receptacle)
 	(Microwave1 - receptacle)
 	(Floor1 - receptacle)
 	(Fridge1 - receptacle)
 )
(:init 
 	(sliceable Lettuce1)
 	(sliceable Potato1)
 	(sliceable Egg1)
 	(sliceable Apple1)
 	(sliceable Potato2)
 	(heatable Potato1)
 	(heatable Egg1)
 	(heatable Cup1)
 	(heatable Apple1)
 	(heatable Potato2)
 	(coolable Lettuce1)
 	(coolable Potato1)
 	(coolable Egg1)
 	(coolable Apple1)
 	(coolable Potato2)
 	(objectAtLocation Spatula1 Floor1)
 	(objectAtLocation Potato1 Plate1)
 	(objectAtLocation Potato2 Pot1)
 	(objectAtLocation Egg1 Pot2)
 	(objectAtLocation Knife1 Plate2)
 	(objectAtLocation Apple1 CounterTop1)
 	(objectAtLocation Fork1 Mug1)
 	(objectAtLocation DishSponge1 Plate3)
 	(objectAtLocation Fork2 CounterTop2)
 	(objectAtLocation Spoon1 Bowl1)
 	(objectAtLocation Lettuce1 Plate4)
 	(objectAtLocation Cup1 Cabinet1)
 	(objectAtLocation Fork3 SinkBasin1)
 	(objectAtLocation SoapBottle1 Cabinet2)
 )
Output:
(:goal (and
                (objectAtLocation Spatula1 Cabinet1)
                (objectAtLocation Potato1 Cabinet1)
                (objectAtLocation Potato2 Cabinet1)
                (objectAtLocation Egg1 Cabinet1)
                (objectAtLocation Knife1 Cabinet1)
                (objectAtLocation Apple1 Cabinet1)
                (objectAtLocation Fork1 Cabinet1)
                (objectAtLocation DishSponge1 Cabinet1)
                (objectAtLocation Fork2 Cabinet1)
                (objectAtLocation Spoon1 Cabinet1)
                (objectAtLocation Lettuce1 Fridge1)
                (objectAtLocation Cup1 Cabinet1)
                (objectAtLocation Fork3 Cabinet1)
                (objectAtLocation SoapBottle1 CounterTop1)
            )
        )