
########### scene6 - 8 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Spoon1 - object)
 	(DishSponge1 - object)
 	(Spatula1 - object)
 	(Knife1 - object)
 	(Bread1 - object)
 	(Mug2 - object)
 	(Plate1 - object)
 	(Potato1 - object)
 	(Egg1 - object)
 	(Mug1 - object)
 	(Apple1 - object)
 	(ButterKnife1 - object)
 	(Fridge1 - receptacle)
 	(Cabinet1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Microwave1 - receptacle)
 	(Pot3 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(Pot1 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Cup1 - receptacle)
 	(CoffeeMachine1 - receptacle)
 	(Pot2 - receptacle)
 	(Oven1 - receptacle)
 	(Floor1 - receptacle)
 )
(:init 
 	(sliceable Egg1)
 	(sliceable Bread1)
 	(sliceable Apple1)
 	(sliceable Potato1)
 	(heatable Bread1)
 	(heatable Potato1)
 	(heatable Egg1)
 	(heatable Cup1)
 	(heatable Apple1)
 	(coolable Egg1)
 	(coolable Bread1)
 	(coolable Apple1)
 	(coolable Potato1)
 	(objectAtLocation Spoon1 Floor1)
 	(objectAtLocation ButterKnife1 Bowl1)
 	(objectAtLocation Plate1 SinkBasin1)
 	(objectAtLocation Egg1 Pot1)
 	(objectAtLocation DishSponge1 Cabinet1)
 	(objectAtLocation Bread1 GarbageCan1)
 	(objectAtLocation Spatula1 SinkBasin2)
 	(objectAtLocation Knife1 Pot2)
 	(objectAtLocation Apple1 Microwave1)
 	(objectAtLocation Mug1 CoffeeMachine1)
 	(objectAtLocation Mug2 Fridge1)
 	(objectAtLocation Potato1 Pot3)
 )
Output:
(:goal (and
                (objectAtLocation Spoon1 Cabinet1)
                (objectAtLocation DishSponge1 Cabinet1)
                (objectAtLocation Spatula1 Cabinet1)
                (objectAtLocation Knife1 Cabinet1)
                (objectAtLocation Bread1 Cabinet1)
                (objectAtLocation Mug2 Cabinet1)
                (objectAtLocation Plate1 Cabinet1)
                (objectAtLocation Potato1 Cabinet1)
                (objectAtLocation Egg1 Cabinet1)
                (objectAtLocation Mug1 Cabinet1)
                (objectAtLocation Apple1 Cabinet1)
                (objectAtLocation ButterKnife1 Cabinet1)
            )
        )