
########### scene6 - 19 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Spoon1 - object)
 	(DishSponge1 - object)
 	(Knife1 - object)
 	(Bread1 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Knife2 - object)
 	(Egg3 - object)
 	(Knife3 - object)
 	(Spoon2 - object)
 	(Spoon3 - object)
 	(Potato1 - object)
 	(Egg1 - object)
 	(Egg2 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Pan2 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Pot2 - receptacle)
 	(Microwave1 - receptacle)
 	(Pot3 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(Plate1 - receptacle)
 	(Pot1 - receptacle)
 	(Bowl2 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Mug1 - receptacle)
 	(Pan1 - receptacle)
 	(Oven1 - receptacle)
 	(Floor1 - receptacle)
 )
(:init 
 	(sliceable Bread1)
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Egg3)
 	(sliceable Potato1)
 	(sliceable Egg1)
 	(sliceable Egg2)
 	(heatable Bread1)
 	(heatable Egg3)
 	(heatable Tomato1)
 	(heatable Potato1)
 	(heatable Egg1)
 	(heatable Egg2)
 	(coolable Bread1)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Egg3)
 	(coolable Potato1)
 	(coolable Egg1)
 	(coolable Egg2)
 	(objectAtLocation Egg1 Floor1)
 	(objectAtLocation Spoon1 Mug1)
 	(objectAtLocation Lettuce1 SinkBasin1)
 	(objectAtLocation Fork1 Pot1)
 	(objectAtLocation Spoon2 Plate1)
 	(objectAtLocation Knife1 SinkBasin2)
 	(objectAtLocation Bread1 Microwave1)
 	(objectAtLocation Knife2 Bowl2)
 	(objectAtLocation Tomato1 Fridge1)
 	(objectAtLocation DishSponge1 CounterTop1)
 	(objectAtLocation Spoon3 Pan1)
 	(objectAtLocation Egg2 Pot2)
 	(objectAtLocation Egg3 GarbageCan1)
 	(objectAtLocation Potato1 Pot3)
 	(objectAtLocation Knife3 Pan2)
 )
Output:
(:goal (and
                (objectAtLocation Egg1 Fridge1)
                (objectAtLocation Spoon1 Cabinet1)
                (objectAtLocation Lettuce1 Fridge1)
                (objectAtLocation Fork1 Cabinet1)
                (objectAtLocation Spoon2 Cabinet1)
                (objectAtLocation Knife1 Cabinet1)
                (objectAtLocation Bread1 Fridge1)
                (objectAtLocation Knife2 Cabinet1)
                (objectAtLocation Tomato1 Fridge1)
                (objectAtLocation DishSponge1 CounterTop1)
                (objectAtLocation Spoon3 Cabinet1)
                (objectAtLocation Egg2 Fridge1)
                (objectAtLocation Egg3 GarbageCan1)
                (objectAtLocation Potato1 Fridge1)
                (objectAtLocation Knife3 Cabinet1)
            )
        )