
########### scene6 - 17 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Tomato2 - object)
 	(Spoon1 - object)
 	(Tomato3 - object)
 	(Knife1 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Potato3 - object)
 	(Tomato4 - object)
 	(Plate1 - object)
 	(Bowl1 - object)
 	(Bowl2 - object)
 	(Potato1 - object)
 	(Mug1 - object)
 	(Apple1 - object)
 	(Potato2 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Microwave1 - receptacle)
 	(SinkBasin4 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl2 - receptacle)
 	(Bowl1 - receptacle)
 	(SinkBasin3 - receptacle)
 	(Plate1 - receptacle)
 	(Microwave2 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Mug1 - receptacle)
 	(Pan1 - receptacle)
 	(Bowl3 - receptacle)
 	(Oven1 - receptacle)
 	(Floor1 - receptacle)
 )
(:init 
 	(sliceable Tomato2)
 	(sliceable Tomato3)
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Potato3)
 	(sliceable Tomato4)
 	(sliceable Potato1)
 	(sliceable Apple1)
 	(sliceable Potato2)
 	(heatable Tomato2)
 	(heatable Tomato3)
 	(heatable Potato3)
 	(heatable Tomato1)
 	(heatable Tomato4)
 	(heatable Potato1)
 	(heatable Apple1)
 	(heatable Potato2)
 	(coolable Tomato2)
 	(coolable Tomato3)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Potato3)
 	(coolable Tomato4)
 	(coolable Potato1)
 	(coolable Apple1)
 	(coolable Potato2)
 	(objectAtLocation Apple1 Floor1)
 	(objectAtLocation Mug1 CounterTop1)
 	(objectAtLocation Tomato1 Pan1)
 	(objectAtLocation Tomato2 Bowl1)
 	(objectAtLocation Knife1 Bowl2)
 	(objectAtLocation Tomato3 Microwave1)
 	(objectAtLocation Plate1 CounterTop2)
 	(objectAtLocation Bowl1 Microwave2)
 	(objectAtLocation Potato1 Fridge1)
 	(objectAtLocation Spoon1 Mug1)
 	(objectAtLocation Lettuce1 SinkBasin1)
 	(objectAtLocation Bowl2 SinkBasin2)
 	(objectAtLocation Tomato4 SinkBasin3)
 	(objectAtLocation Potato2 Bowl3)
 	(objectAtLocation Potato3 Plate1)
 )
Output:
(:goal (and
                (objectAtLocation Apple1 Fridge1)
                (objectAtLocation Mug1 Cabinet1)
                (objectAtLocation Tomato1 Fridge1)
                (objectAtLocation Tomato2 Fridge1)
                (objectAtLocation Knife1 CounterTop1)
                (objectAtLocation Tomato3 Fridge1)
                (objectAtLocation Plate1 Cabinet1)
                (objectAtLocation Bowl1 Cabinet1)
                (objectAtLocation Potato1 Fridge1)
                (objectAtLocation Spoon1 Cabinet1)
                (objectAtLocation Lettuce1 Fridge1)
                (objectAtLocation Bowl2 Cabinet1)
                (objectAtLocation Tomato4 Fridge1)
                (objectAtLocation Potato2 Fridge1)
                (objectAtLocation Potato3 Fridge1)
            )
        )