
########### scene6 - 1 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(SoapBottle1 - object)
 	(Spatula1 - object)
 	(Potato2 - object)
 	(Bread1 - object)
 	(Tomato1 - object)
 	(Plate1 - object)
 	(Bowl1 - object)
 	(Pan1 - object)
 	(Potato1 - object)
 	(Egg1 - object)
 	(Apple1 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Cabinet1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Pot2 - receptacle)
 	(Microwave1 - receptacle)
 	(Fridge2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Pot1 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Mug1 - receptacle)
 	(GarbageCan2 - receptacle)
 	(Oven1 - receptacle)
 	(Floor1 - receptacle)
 )
(:init 
 	(sliceable Bread1)
 	(sliceable Tomato1)
 	(sliceable Potato1)
 	(sliceable Egg1)
 	(sliceable Apple1)
 	(sliceable Potato2)
 	(heatable Bread1)
 	(heatable Tomato1)
 	(heatable Potato1)
 	(heatable Egg1)
 	(heatable Apple1)
 	(heatable Potato2)
 	(coolable Bread1)
 	(coolable Tomato1)
 	(coolable Potato1)
 	(coolable Egg1)
 	(coolable Apple1)
 	(coolable Potato2)
 	(objectAtLocation Egg1 Floor1)
 	(objectAtLocation SoapBottle1 Cabinet1)
 	(objectAtLocation Plate1 Microwave1)
 	(objectAtLocation ButterKnife1 Mug1)
 	(objectAtLocation Bread1 GarbageCan1)
 	(objectAtLocation Potato1 SinkBasin1)
 	(objectAtLocation Bowl1 Fridge1)
 	(objectAtLocation Apple1 CounterTop1)
 	(objectAtLocation Spatula1 SinkBasin2)
 	(objectAtLocation Tomato1 Pot1)
 	(objectAtLocation Potato2 GarbageCan2)
 	(objectAtLocation Pan1 Fridge2)
 )
Output:
(:goal (and
                (objectAtLocation Egg1 Fridge1)
                (objectAtLocation SoapBottle1 Cabinet1)
                (objectAtLocation Plate1 Cabinet1)
                (objectAtLocation ButterKnife1 Cabinet1)
                (objectAtLocation Bread1 Fridge1)
                (objectAtLocation Potato1 Fridge1)
                (objectAtLocation Bowl1 Cabinet1)
                (objectAtLocation Apple1 Fridge1)
                (objectAtLocation Spatula1 Cabinet1)
                (objectAtLocation Tomato1 Fridge1)
                (objectAtLocation Potato2 Fridge1)
                (objectAtLocation Pan1 Cabinet1)
            )
        )