
########### food_pre4 - 15 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(DishSponge2 - object)
 	(DishSponge1 - object)
 	(Knife1 - object)
 	(PepperShaker1 - object)
 	(Mug2 - object)
 	(Lettuce1 - object)
 	(Knife2 - object)
 	(Potato1 - object)
 	(Egg1 - object)
 	(Mug1 - object)
 	(Apple1 - object)
 	(Egg2 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(CounterTop3 - receptacle)
 	(CounterTop4 - receptacle)
 	(Fridge2 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(Plate1 - receptacle)
 	(Plate2 - receptacle)
 	(Pan1 - receptacle)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Lettuce1)
 	(sliceable Potato1)
 	(sliceable Egg1)
 	(sliceable Apple1)
 	(sliceable Egg2)
 	(heatable Egg1)
 	(heatable Apple1)
 	(heatable Egg2)
 	(heatable Potato1)
 	(coolable Lettuce1)
 	(coolable Potato1)
 	(coolable Egg1)
 	(coolable Apple1)
 	(coolable Egg2)
 	(objectAtLocation DishSponge1 Bowl1)
 	(objectAtLocation Knife1 Pan1)
 	(objectAtLocation Egg1 Plate1)
 	(objectAtLocation DishSponge2 GarbageCan1)
 	(objectAtLocation Lettuce1 Fridge1)
 	(objectAtLocation Mug1 SinkBasin1)
 	(objectAtLocation Knife2 Plate2)
 	(objectAtLocation Potato1 CounterTop1)
 	(objectAtLocation Egg2 Fridge2)
 	(objectAtLocation Apple1 CounterTop2)
 	(objectAtLocation Mug2 CounterTop3)
 	(objectAtLocation PepperShaker1 CounterTop4)
 )
Output:
(:goal (and
                (objectAtLocation Egg1 DiningTable1)
                (objectAtLocation Apple1 DiningTable1)
                (objectAtLocation Potato1 DiningTable1)
                (objectAtLocation Lettuce1 DiningTable1)
                (objectAtLocation Egg2 DiningTable1)
            )
        )
****** Goal in Natural Language query ********
Write the goal specification in natural language.
Output:
(:goal (and
        (objectAtLocation Egg1 DiningTable1)
        (objectAtLocation Potato1 DiningTable1)
        (objectAtLocation Lettuce1 DiningTable1)
        (objectAtLocation Apple1 DiningTable1)
    )
)
******* Domain understanding query ********
What does "prepare a meal" mean? What are the relevant objects for preparing a meal?
Output:
(:goal (and
        (objectAtLocation Egg1 DiningTable1)
        (objectAtLocation Apple1 DiningTable1)
        (objectAtLocation Potato1 DiningTable1)
        (isSliced Egg1)
        (isSliced Apple1)
        (isSliced Potato1)
        (isHot Egg1)
        (isHot Apple1)
        (isHot Potato1)
    )
)