
########### food_pre4 - 8 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(DishSponge2 - object)
 	(Spoon1 - object)
 	(DishSponge1 - object)
 	(Knife1 - object)
 	(Potato2 - object)
 	(Bread1 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Bowl1 - object)
 	(Plate1 - object)
 	(Ladle1 - object)
 	(Potato1 - object)
 	(Cup1 - object)
 	(Apple1 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Pan2 - receptacle)
 	(Cabinet3 - receptacle)
 	(Cabinet1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Microwave1 - receptacle)
 	(Cabinet2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(Plate1 - receptacle)
 	(Pot1 - receptacle)
 	(Microwave2 - receptacle)
 	(Plate2 - receptacle)
 	(Pan1 - receptacle)
 	(Egg1 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Bread1)
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Potato1)
 	(sliceable Apple1)
 	(sliceable Potato2)
 	(heatable Bread1)
 	(heatable Tomato1)
 	(heatable Potato1)
 	(heatable Cup1)
 	(heatable Apple1)
 	(heatable Potato2)
 	(coolable Bread1)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Potato1)
 	(coolable Apple1)
 	(coolable Potato2)
 	(objectAtLocation Ladle1 Cabinet1)
 	(objectAtLocation Cup1 Cabinet2)
 	(objectAtLocation Plate1 Microwave1)
 	(objectAtLocation Bread1 Microwave2)
 	(objectAtLocation Bowl1 CounterTop1)
 	(objectAtLocation Lettuce1 Fridge1)
 	(objectAtLocation Knife1 Bowl1)
 	(objectAtLocation Tomato1 Pan1)
 	(objectAtLocation DishSponge1 GarbageCan1)
 	(objectAtLocation Apple1 Pan2)
 	(objectAtLocation Spoon1 Plate1)
 	(objectAtLocation ButterKnife1 SinkBasin1)
 	(objectAtLocation Potato1 Pot1)
 	(objectAtLocation DishSponge2 Cabinet3)
 	(objectAtLocation Potato2 Plate2)
 	(objectAtLocation Egg1 Bowl1)
 )
Output:
```pddl
(goal
    (exists (?o - object ?t - receptacle)
        (and
            (objectAtLocation ?o ?t)
            (isDiningTable ?t)
        )
    )
)
```