
########### food_pre4 - 7 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Spoon1 - object)
 	(DishSponge1 - object)
 	(Tomato1 - object)
 	(Ladle1 - object)
 	(Pot1 - object)
 	(Potato1 - object)
 	(Apple2 - object)
 	(Apple1 - object)
 	(SaltShaker1 - object)
 	(ButterKnife1 - object)
 	(Fridge1 - receptacle)
 	(Cabinet1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Microwave1 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(Pot1 - receptacle)
 	(Plate2 - receptacle)
 	(Cup1 - receptacle)
 	(Pot2 - receptacle)
 	(Pan1 - receptacle)
 	(Egg1 - object)
 	(Lettuce1 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Potato1)
 	(sliceable Apple2)
 	(sliceable Tomato1)
 	(sliceable Apple1)
 	(heatable Tomato1)
 	(heatable Potato1)
 	(heatable Cup1)
 	(heatable Apple2)
 	(heatable Apple1)
 	(coolable Potato1)
 	(coolable Apple2)
 	(coolable Tomato1)
 	(coolable Apple1)
 	(objectAtLocation ButterKnife1 Plate1)
 	(objectAtLocation Ladle1 SinkBasin1)
 	(objectAtLocation SaltShaker1 Cabinet1)
 	(objectAtLocation Spoon1 Cup1)
 	(objectAtLocation Pot1 Fridge1)
 	(objectAtLocation DishSponge1 Pot1)
 	(objectAtLocation Tomato1 GarbageCan1)
 	(objectAtLocation Fork1 Pot2)
 	(objectAtLocation Apple1 Microwave1)
 	(objectAtLocation Apple2 Plate2)
 	(objectAtLocation Potato1 Pan1)
 	(objectAtLocation Egg1 Cabinet1)
 	(objectAtLocation Lettuce1 SinkBasin1)
 )
Output:
(:goal (and
        (isHot Tomato1)
        (isHot Potato1)
        (isHot Cup1)
        (isHot Apple2)
        (isHot Apple1)
        (objectAtLocation Tomato1 DiningTable1)
        (objectAtLocation Potato1 DiningTable1)
        (objectAtLocation Cup1 DiningTable1)
        (objectAtLocation Apple2 DiningTable1)
        (objectAtLocation Apple1 DiningTable1)
    )
)
****** Goal in Natural Language query ********
Write the goal specification in natural language.
Output:
(:goal (and
        (inReceptacle Tomato1 Plate1)
        (inReceptacle Potato1 Plate1)
        (inReceptacle Apple1 Plate1)
        (inReceptacle Apple2 Plate1)
        (inReceptacle Egg1 Plate1)
        (inReceptacle Lettuce1 Plate1)
    )
)
******* Domain understanding query ********
What does "prepare a meal" mean? What are the relevant objects for preparing a meal?
Output:
(:goal (and
	(isSliced Tomato1)
	(isSliced Potato1)
	(isSliced Apple1)
	(isSliced Apple2)
	(isHot Tomato1)
	(isHot Potato1)
	(isHot Apple1)
	(isHot Apple2)
	(inReceptacle Tomato1 DiningTable1)
	(inReceptacle Potato1 DiningTable1)
	(inReceptacle Apple1 DiningTable1)
	(inReceptacle Apple2 DiningTable1)
))