
########### food_pre4 - 16 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Spoon1 - object)
 	(PepperShaker1 - object)
 	(Potato2 - object)
 	(Lettuce1 - object)
 	(Plate1 - object)
 	(ButterKnife2 - object)
 	(Potato1 - object)
 	(Egg1 - object)
 	(Apple1 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Microwave1 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(Pot1 - receptacle)
 	(Microwave2 - receptacle)
 	(Plate2 - receptacle)
 	(Mug1 - receptacle)
 	(Pan1 - receptacle)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Lettuce1)
 	(sliceable Potato1)
 	(sliceable Egg1)
 	(sliceable Apple1)
 	(sliceable Potato2)
 	(heatable Potato2)
 	(heatable Egg1)
 	(heatable Apple1)
 	(heatable Potato1)
 	(coolable Lettuce1)
 	(coolable Potato1)
 	(coolable Egg1)
 	(coolable Apple1)
 	(coolable Potato2)
 	(objectAtLocation Spoon1 Mug1)
 	(objectAtLocation ButterKnife1 Plate1)
 	(objectAtLocation ButterKnife2 Pot1)
 	(objectAtLocation PepperShaker1 CounterTop1)
 	(objectAtLocation Lettuce1 Pan1)
 	(objectAtLocation Egg1 SinkBasin1)
 	(objectAtLocation Potato1 Microwave1)
 	(objectAtLocation Potato2 Fridge1)
 	(objectAtLocation Plate1 Microwave2)
 	(objectAtLocation Apple1 Plate2)
 )
Output:
(:goal (and
        (objectAtLocation Plate1 DiningTable1)
    )
)
****** Goal in Natural Language query ********
Write the goal specification in natural language.
Output:
(:goal (and
        (isSliced Lettuce1)
        (isSliced Potato1)
        (isSliced Apple1)
        (isHot Potato2)
        (isHot Egg1)
        (isHot Apple1)
        (isHot Potato1)
        (inReceptacle Lettuce1 DiningTable1)
        (inReceptacle Potato1 DiningTable1)
        (inReceptacle Apple1 DiningTable1)
        (inReceptacle Potato2 DiningTable1)
        (inReceptacle Egg1 DiningTable1)
    )
)
******* Domain understanding query ********
What does "prepare a meal" mean? What are the relevant objects for preparing a meal?
Output:
(:goal (and
        (isSliced Lettuce1)
        (isSliced Potato1)
        (isSliced Egg1)
        (isSliced Apple1)
        (isSliced Potato2)
        (isHot Potato2)
        (isHot Egg1)
        (isHot Apple1)
        (isHot Potato1)
        (isCool Lettuce1)
        (isCool Potato1)
        (isCool Egg1)
        (isCool Apple1)
        (isCool Potato2)
        (inReceptacle Lettuce1 DiningTable1)
        (inReceptacle Potato1 DiningTable1)
        (inReceptacle Egg1 DiningTable1)
        (inReceptacle Apple1 DiningTable1)
        (inReceptacle Potato2 DiningTable1)
    )
)