
########### food_pre4 - 19 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Spoon1 - object)
 	(Lettuce2 - object)
 	(Spatula2 - object)
 	(Spatula1 - object)
 	(DishSponge1 - object)
 	(Bread1 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Bread2 - object)
 	(Ladle1 - object)
 	(Pot1 - object)
 	(Lettuce3 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(GarbageCan3 - receptacle)
 	(Cabinet1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(Plate1 - receptacle)
 	(Bowl2 - receptacle)
 	(Pot1 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Mug1 - receptacle)
 	(Pan1 - receptacle)
 	(GarbageCan2 - receptacle)
 	(Egg1 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Lettuce2)
 	(sliceable Bread1)
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Bread2)
 	(sliceable Lettuce3)
 	(heatable Bread1)
 	(heatable Tomato1)
 	(heatable Bread2)
 	(coolable Lettuce2)
 	(coolable Bread1)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Bread2)
 	(coolable Lettuce3)
 	(objectAtLocation Tomato1 SinkBasin1)
 	(objectAtLocation Fork1 Mug1)
 	(objectAtLocation Spatula1 Plate1)
 	(objectAtLocation Spatula2 Bowl1)
 	(objectAtLocation Spoon1 Pan1)
 	(objectAtLocation Bread1 GarbageCan1)
 	(objectAtLocation Pot1 SinkBasin2)
 	(objectAtLocation Ladle1 Cabinet1)
 	(objectAtLocation ButterKnife1 Bowl2)
 	(objectAtLocation Bread2 CounterTop1)
 	(objectAtLocation Lettuce1 Pot1)
 	(objectAtLocation Lettuce2 Fridge1)
 	(objectAtLocation DishSponge1 GarbageCan2)
 	(objectAtLocation Lettuce3 GarbageCan3)
 	(objectAtLocation Egg1 CounterTop1)
 )
Output:
```pddl
(goal 
    (exists (?o - object)
        (and
            (objectAtLocation ?o DiningTable1)
        )
    )
)
```