
########### food_pre4 - 2 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Knife1 - object)
 	(Bread1 - object)
 	(Tomato1 - object)
 	(Knife2 - object)
 	(Bread2 - object)
 	(Ladle1 - object)
 	(Pan1 - object)
 	(Egg1 - object)
 	(Apple2 - object)
 	(Apple1 - object)
 	(Egg2 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Plate2 - receptacle)
 	(Pot3 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(Bowl1 - receptacle)
 	(Pot1 - receptacle)
 	(SinkBasin3 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Pot2 - receptacle)
 	(Pot4 - receptacle)
 	(Lettuce1 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Bread1)
 	(sliceable Tomato1)
 	(sliceable Bread2)
 	(sliceable Egg1)
 	(sliceable Apple2)
 	(sliceable Apple1)
 	(sliceable Egg2)
 	(heatable Bread1)
 	(heatable Tomato1)
 	(heatable Bread2)
 	(heatable Egg1)
 	(heatable Apple2)
 	(heatable Apple1)
 	(heatable Egg2)
 	(coolable Bread1)
 	(coolable Tomato1)
 	(coolable Bread2)
 	(coolable Egg1)
 	(coolable Apple2)
 	(coolable Apple1)
 	(coolable Egg2)
 	(objectAtLocation Apple1 SinkBasin1)
 	(objectAtLocation Ladle1 Pot1)
 	(objectAtLocation Egg1 Plate1)
 	(objectAtLocation Tomato1 SinkBasin2)
 	(objectAtLocation ButterKnife1 Pot2)
 	(objectAtLocation Fork1 Pot3)
 	(objectAtLocation Knife1 Plate2)
 	(objectAtLocation Bread1 CounterTop1)
 	(objectAtLocation Knife2 Bowl1)
 	(objectAtLocation Apple2 Fridge1)
 	(objectAtLocation Pan1 SinkBasin3)
 	(objectAtLocation Bread2 GarbageCan1)
 	(objectAtLocation Egg2 Pot4)
 	(objectAtLocation Lettuce1 GarbageCan1)
 )
Output:
```pddl
(:goal (and (objectAtLocation ?o - object DiningTable1)))
```