
########### food_pre4 - 6 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Spoon1 - object)
 	(Spatula1 - object)
 	(Knife1 - object)
 	(Plate2 - object)
 	(Spoon2 - object)
 	(Plate1 - object)
 	(Bowl1 - object)
 	(Pot1 - object)
 	(Egg1 - object)
 	(Cup1 - object)
 	(Apple2 - object)
 	(Apple1 - object)
 	(Egg2 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(CounterTop3 - receptacle)
 	(SinkBasin4 - receptacle)
 	(Microwave1 - receptacle)
 	(Fridge2 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(SinkBasin3 - receptacle)
 	(Plate1 - receptacle)
 	(Bowl2 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Cup1 - receptacle)
 	(Lettuce1 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Egg1)
 	(sliceable Apple2)
 	(sliceable Apple1)
 	(sliceable Egg2)
 	(heatable Egg1)
 	(heatable Cup1)
 	(heatable Apple2)
 	(heatable Apple1)
 	(heatable Egg2)
 	(coolable Egg1)
 	(coolable Apple2)
 	(coolable Apple1)
 	(coolable Egg2)
 	(objectAtLocation Knife1 CounterTop1)
 	(objectAtLocation Plate1 SinkBasin1)
 	(objectAtLocation Fork1 SinkBasin2)
 	(objectAtLocation Spoon1 SinkBasin3)
 	(objectAtLocation Apple1 Bowl1)
 	(objectAtLocation Egg1 Plate1)
 	(objectAtLocation Spatula1 Bowl2)
 	(objectAtLocation Egg2 Fridge1)
 	(objectAtLocation Bowl1 Fridge2)
 	(objectAtLocation Cup1 CounterTop2)
 	(objectAtLocation Spoon2 Cup1)
 	(objectAtLocation Pot1 CounterTop3)
 	(objectAtLocation Apple2 SinkBasin4)
 	(objectAtLocation Plate2 Microwave1)
 	(objectAtLocation Lettuce1 SinkBasin4)
 )
Output:
(:goal (and
        (inReceptacle Egg1 Plate1)
        (inReceptacle Egg2 Plate1)
        (inReceptacle Apple1 Plate1)
        (inReceptacle Apple2 Plate1)
        (objectAtLocation Plate1 DiningTable1)
    )
)
****** Goal in Natural Language query ********
Write the goal specification in natural language.
Output:
(:goal (and
        (inReceptacle Plate1 DiningTable1)
        (inReceptacle Plate2 DiningTable1)
        (isHot Egg1)
        (isHot Apple2)
        (isCool Egg2)
        (isSliced Apple1)
    )
)
******* Domain understanding query ********
What does "prepare a meal" mean? What are the relevant objects for preparing a meal?
Output:
(:goal (and
        (isSliced Apple1)
        (isSliced Apple2)
        (isSliced Egg1)
        (isSliced Egg2)
        (isHot Plate2)
        (inReceptacle Egg1 DiningTable1)
        (inReceptacle Egg2 DiningTable1)
        (inReceptacle Apple1 DiningTable1)
        (inReceptacle Apple2 DiningTable1)
    )
)