
########### food_pre4 - 11 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Tomato2 - object)
 	(Fork1 - object)
 	(Spoon1 - object)
 	(DishSponge1 - object)
 	(Tomato1 - object)
 	(Ladle1 - object)
 	(Egg1 - object)
 	(Cup1 - object)
 	(Cup2 - object)
 	(SaltShaker1 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Pan2 - receptacle)
 	(Cabinet1 - receptacle)
 	(Mug2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(Bowl2 - receptacle)
 	(Pot1 - receptacle)
 	(Mug1 - receptacle)
 	(Pan1 - receptacle)
 	(Lettuce1 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Tomato2)
 	(sliceable Egg1)
 	(sliceable Tomato1)
 	(heatable Tomato2)
 	(heatable Tomato1)
 	(heatable Egg1)
 	(heatable Cup1)
 	(heatable Cup2)
 	(coolable Tomato2)
 	(coolable Egg1)
 	(coolable Tomato1)
 	(objectAtLocation Tomato1 Bowl1)
 	(objectAtLocation Cup1 CounterTop1)
 	(objectAtLocation ButterKnife1 Pan1)
 	(objectAtLocation DishSponge1 Pot1)
 	(objectAtLocation Tomato2 Pan2)
 	(objectAtLocation Fork1 Mug1)
 	(objectAtLocation Egg1 Fridge1)
 	(objectAtLocation Spoon1 Mug2)
 	(objectAtLocation Ladle1 Bowl2)
 	(objectAtLocation SaltShaker1 Cabinet1)
 	(objectAtLocation Cup2 SinkBasin1)
 	(objectAtLocation Lettuce1 CounterTop1)
 )
Output:
(:goal (and
        (isSliced Tomato1)
        (isSliced Tomato2)
        (isSliced Egg1)
        (isSliced Lettuce1)
        (isHot Tomato1)
        (isHot Tomato2)
        (isHot Egg1)
        (objectAtLocation Tomato1 DiningTable1)
        (objectAtLocation Tomato2 DiningTable1)
        (objectAtLocation Egg1 DiningTable1)
        (objectAtLocation Lettuce1 DiningTable1)
    )
)
****** Goal in Natural Language query ********
Write the goal specification in natural language.
Output:
(:goal (and
        (isHot Tomato1)
        (isHot Tomato2)
        (isHot Egg1)
        (inReceptacle Tomato1 DiningTable1)
        (inReceptacle Tomato2 DiningTable1)
        (inReceptacle Egg1 DiningTable1)
       )
)
******* Domain understanding query ********
What does "prepare a meal" mean? What are the relevant objects for preparing a meal?
Output:
(:goal (and
                (isSliced Tomato1)
                (isSliced Tomato2)
                (isSliced Lettuce1)
                (isHot Egg1)
                (objectAtLocation Tomato1 DiningTable1)
                (objectAtLocation Tomato2 DiningTable1)
                (objectAtLocation Lettuce1 DiningTable1)
                (objectAtLocation Egg1 DiningTable1)
            )
        )