
########### food_pre4 - 3 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Spoon1 - object)
 	(SoapBottle1 - object)
 	(Spatula1 - object)
 	(Knife1 - object)
 	(Knife3 - object)
 	(Tomato1 - object)
 	(Knife2 - object)
 	(Knife4 - object)
 	(Ladle1 - object)
 	(Fork2 - object)
 	(Apple2 - object)
 	(Apple1 - object)
 	(Fridge1 - receptacle)
 	(Cabinet1 - receptacle)
 	(Mug1 - receptacle)
 	(Mug2 - receptacle)
 	(Pot3 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl2 - receptacle)
 	(Bowl1 - receptacle)
 	(Pot1 - receptacle)
 	(Cup1 - receptacle)
 	(Pot2 - receptacle)
 	(Pan1 - receptacle)
 	(Bowl3 - receptacle)
 	(Egg1 - object)
 	(Lettuce1 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Tomato1)
 	(sliceable Apple2)
 	(sliceable Apple1)
 	(heatable Cup1)
 	(heatable Apple2)
 	(heatable Apple1)
 	(heatable Tomato1)
 	(coolable Tomato1)
 	(coolable Apple2)
 	(coolable Apple1)
 	(objectAtLocation Spoon1 Mug1)
 	(objectAtLocation Knife1 Bowl1)
 	(objectAtLocation Knife2 Pot1)
 	(objectAtLocation Apple1 Bowl2)
 	(objectAtLocation Ladle1 Pot2)
 	(objectAtLocation Fork1 Cup1)
 	(objectAtLocation Knife3 Pan1)
 	(objectAtLocation Knife4 Mug2)
 	(objectAtLocation Fork2 Bowl3)
 	(objectAtLocation Tomato1 SinkBasin1)
 	(objectAtLocation Spatula1 Pot3)
 	(objectAtLocation SoapBottle1 Cabinet1)
 	(objectAtLocation Apple2 Fridge1)
 	(objectAtLocation Egg1 Pot2)
 	(objectAtLocation Lettuce1 Pan1)
 )
Output:
(:goal (and
        (objectAtLocation Apple1 DiningTable1)
        (objectAtLocation Apple2 DiningTable1)
        (objectAtLocation Tomato1 DiningTable1)
        (objectAtLocation Egg1 DiningTable1)
        (objectAtLocation Lettuce1 DiningTable1)
    )
)
****** Goal in Natural Language query ********
Write the goal specification in natural language.
Output:
(:goal (and
        (objectAtLocation Tomato1 DiningTable1)
        (objectAtLocation Apple1 DiningTable1)
        (objectAtLocation Apple2 DiningTable1)
        (objectAtLocation Egg1 DiningTable1)
        (objectAtLocation Lettuce1 DiningTable1)
    )
)
******* Domain understanding query ********
What does "prepare a meal" mean? What are the relevant objects for preparing a meal?
Output:
(:goal (and
        (inReceptacle Tomato1 DiningTable1)
        (inReceptacle Apple1 DiningTable1)
        (inReceptacle Apple2 DiningTable1)
        (inReceptacle Egg1 DiningTable1)
        (inReceptacle Lettuce1 DiningTable1)
    )
)