
########### food_pre4 - 18 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(DishSponge1 - object)
 	(Spatula1 - object)
 	(Knife1 - object)
 	(Tomato1 - object)
 	(Bowl1 - object)
 	(Ladle1 - object)
 	(ButterKnife2 - object)
 	(Pan1 - object)
 	(Egg1 - object)
 	(Cup1 - object)
 	(Apple2 - object)
 	(Apple1 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Pan2 - receptacle)
 	(Cabinet1 - receptacle)
 	(Microwave1 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(Plate1 - receptacle)
 	(Bowl2 - receptacle)
 	(Plate2 - receptacle)
 	(Cup1 - receptacle)
 	(Pan1 - receptacle)
 	(Bowl3 - receptacle)
 	(Lettuce1 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Egg1)
 	(sliceable Tomato1)
 	(sliceable Apple2)
 	(sliceable Apple1)
 	(heatable Tomato1)
 	(heatable Egg1)
 	(heatable Cup1)
 	(heatable Apple2)
 	(heatable Apple1)
 	(coolable Egg1)
 	(coolable Tomato1)
 	(coolable Apple2)
 	(coolable Apple1)
 	(objectAtLocation Ladle1 Pan1)
 	(objectAtLocation Knife1 CounterTop1)
 	(objectAtLocation Apple1 Pan2)
 	(objectAtLocation Bowl1 Cabinet1)
 	(objectAtLocation Egg1 Bowl1)
 	(objectAtLocation Apple2 Plate1)
 	(objectAtLocation Spatula1 Bowl2)
 	(objectAtLocation Cup1 Microwave1)
 	(objectAtLocation ButterKnife1 Cup1)
 	(objectAtLocation Tomato1 Plate2)
 	(objectAtLocation ButterKnife2 Bowl3)
 	(objectAtLocation Pan1 SinkBasin1)
 	(objectAtLocation DishSponge1 CounterTop2)
 	(objectAtLocation Lettuce1 Pan1)
 )
Output:
(:goal (and
        (objectAtLocation Egg1 DiningTable1)
        (objectAtLocation Tomato1 DiningTable1)
        (objectAtLocation Apple2 DiningTable1)
        (objectAtLocation Apple1 DiningTable1)
        (objectAtLocation Cup1 DiningTable1)
        (objectAtLocation Lettuce1 DiningTable1)
    )
)
****** Goal in Natural Language query ********
Write the goal specification in natural language.
Output:
(:goal (and
        (inReceptacle Tomato1 DiningTable1)
        (inReceptacle Egg1 DiningTable1)
        (inReceptacle Apple2 DiningTable1)
        (inReceptacle Apple1 DiningTable1)
        (inReceptacle Lettuce1 DiningTable1)
    )
)
******* Domain understanding query ********
What does "prepare a meal" mean? What are the relevant objects for preparing a meal?
Output:
(:goal (and
        (isSliced Tomato1)
        (isSliced Apple1)
        (isSliced Apple2)
        (isSliced Egg1)
        (isSliced Lettuce1)
        (isHot Tomato1)
        (isHot Egg1)
        (isHot Cup1)
        (isHot Apple2)
        (isHot Apple1)
        (inReceptacle Tomato1 DiningTable1)
        (inReceptacle Apple1 DiningTable1)
        (inReceptacle Apple2 DiningTable1)
        (inReceptacle Egg1 DiningTable1)
        (inReceptacle Lettuce1 DiningTable1)
        (inReceptacle Cup1 DiningTable1)
    )
)