
########### food_pre4 - 10 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Spoon1 - object)
 	(Spatula2 - object)
 	(Spatula1 - object)
 	(Knife1 - object)
 	(Tomato1 - object)
 	(Bowl1 - object)
 	(Bowl2 - object)
 	(Spatula3 - object)
 	(Cup1 - object)
 	(Cup2 - object)
 	(Mug1 - object)
 	(Pan1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Cabinet1 - receptacle)
 	(Mug1 - receptacle)
 	(Microwave1 - receptacle)
 	(Mug2 - receptacle)
 	(Pot3 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(Bowl1 - receptacle)
 	(Pot1 - receptacle)
 	(Pot2 - receptacle)
 	(Egg1 - object)
 	(Lettuce1 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Tomato1)
 	(heatable Cup1)
 	(heatable Cup2)
 	(heatable Tomato1)
 	(coolable Tomato1)
 	(objectAtLocation Spatula1 Pot1)
 	(objectAtLocation Tomato1 Pot2)
 	(objectAtLocation Bowl1 Microwave1)
 	(objectAtLocation Cup1 Fridge1)
 	(objectAtLocation Spatula2 Plate1)
 	(objectAtLocation Spoon1 Mug1)
 	(objectAtLocation Pan1 CounterTop1)
 	(objectAtLocation Knife1 Mug2)
 	(objectAtLocation Bowl2 CounterTop2)
 	(objectAtLocation Fork1 Pot3)
 	(objectAtLocation Mug1 SinkBasin1)
 	(objectAtLocation Cup2 Cabinet1)
 	(objectAtLocation Spatula3 Bowl1)
 	(objectAtLocation Egg1 Microwave1)
 	(objectAtLocation Lettuce1 Fridge1)
 )
Output:
(:goal (and
                (inReceptacle Tomato1 DiningTable1)
                (inReceptacle Egg1 DiningTable1)
                (inReceptacle Lettuce1 DiningTable1)
                (isSliced Tomato1)
                (isSliced Lettuce1)
                (isHot Egg1)
            )
        )
****** Goal in Natural Language query ********
Write the goal specification in natural language.
Output:
(:goal (and
        (isHeated Tomato1)
        (isHeated Egg1)
        (isHeated Cup1)
        (isHeated Cup2)
        (inReceptacle Tomato1 DiningTable1)
        (inReceptacle Egg1 DiningTable1)
        (inReceptacle Cup1 DiningTable1)
        (inReceptacle Cup2 DiningTable1)
    )
)
******* Domain understanding query ********
What does "prepare a meal" mean? What are the relevant objects for preparing a meal?
Output:
(:goal (and
                (isSliced Tomato1)
                (isSliced Lettuce1)
                (isHot Egg1)
                (inReceptacle Tomato1 DiningTable1)
                (inReceptacle Lettuce1 DiningTable1)
                (inReceptacle Egg1 DiningTable1)
            )
        )