
########### food_pre4 - 1 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(DishSponge1 - object)
 	(Ladle2 - object)
 	(Knife1 - object)
 	(Tomato1 - object)
 	(Plate1 - object)
 	(Ladle1 - object)
 	(Pot1 - object)
 	(ButterKnife1 - object)
 	(Potato1 - object)
 	(Fork2 - object)
 	(Egg1 - object)
 	(Cup1 - object)
 	(Mug1 - object)
 	(Fork3 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Pan2 - receptacle)
 	(CounterTop3 - receptacle)
 	(Microwave1 - receptacle)
 	(Plate3 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(Bowl1 - receptacle)
 	(Bowl2 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Plate2 - receptacle)
 	(Mug1 - receptacle)
 	(Pan1 - receptacle)
 	(Lettuce1 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Egg1)
 	(sliceable Tomato1)
 	(sliceable Potato1)
 	(heatable Egg1)
 	(heatable Cup1)
 	(heatable Tomato1)
 	(heatable Potato1)
 	(coolable Egg1)
 	(coolable Tomato1)
 	(coolable Potato1)
 	(objectAtLocation Mug1 Fridge1)
 	(objectAtLocation Egg1 Plate1)
 	(objectAtLocation Ladle1 CounterTop1)
 	(objectAtLocation DishSponge1 SinkBasin1)
 	(objectAtLocation Tomato1 Pan1)
 	(objectAtLocation Cup1 CounterTop2)
 	(objectAtLocation Fork1 Mug1)
 	(objectAtLocation Fork2 Plate2)
 	(objectAtLocation Ladle2 Bowl1)
 	(objectAtLocation Plate1 Microwave1)
 	(objectAtLocation Potato1 Plate3)
 	(objectAtLocation Fork3 Bowl2)
 	(objectAtLocation Knife1 CounterTop3)
 	(objectAtLocation Pot1 SinkBasin2)
 	(objectAtLocation ButterKnife1 Pan2)
 	(objectAtLocation Lettuce1 Plate1)
 )
Output:
(:goal (and
        (objectAtLocation Egg1 DiningTable1)
        (objectAtLocation Tomato1 DiningTable1)
        (objectAtLocation Potato1 DiningTable1)
        (objectAtLocation Lettuce1 DiningTable1)
        (isSliced Tomato1)
        (isSliced Potato1)
        (isSliced Lettuce1)
        (isHot Egg1)
        (isHot Tomato1)
        (isHot Potato1)
    )
)
****** Goal in Natural Language query ********
Write the goal specification in natural language.
Output:
(:goal (and
                (objectAtLocation Egg1 DiningTable1)
                (objectAtLocation Tomato1 DiningTable1)
                (objectAtLocation Potato1 DiningTable1)
                (objectAtLocation Lettuce1 DiningTable1)
            )
        )
******* Domain understanding query ********
What does "prepare a meal" mean? What are the relevant objects for preparing a meal?
Output:
(:goal (and
        (isSliced Tomato1)
        (isSliced Potato1)
        (isSliced Lettuce1)
        (isHot Egg1)
        (inReceptacle Tomato1 DiningTable1)
        (inReceptacle Potato1 DiningTable1)
        (inReceptacle Lettuce1 DiningTable1)
        (inReceptacle Egg1 DiningTable1)
    )
)