
########### food_pre4 - 5 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Spoon1 - object)
 	(DishSponge1 - object)
 	(Knife1 - object)
 	(Ladle2 - object)
 	(Pot2 - object)
 	(Ladle1 - object)
 	(Pot1 - object)
 	(Potato1 - object)
 	(Egg1 - object)
 	(Mug1 - object)
 	(Pan1 - object)
 	(Egg2 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Pan2 - receptacle)
 	(Cabinet1 - receptacle)
 	(CounterTop3 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(Plate1 - receptacle)
 	(Pan3 - receptacle)
 	(Pot1 - receptacle)
 	(Plate2 - receptacle)
 	(Pan1 - receptacle)
 	(Lettuce1 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Egg1)
 	(sliceable Egg2)
 	(sliceable Potato1)
 	(heatable Egg1)
 	(heatable Egg2)
 	(heatable Potato1)
 	(coolable Egg1)
 	(coolable Egg2)
 	(coolable Potato1)
 	(objectAtLocation Egg1 Bowl1)
 	(objectAtLocation Egg2 CounterTop1)
 	(objectAtLocation Ladle1 Pan1)
 	(objectAtLocation Spoon1 Pan2)
 	(objectAtLocation Knife1 Plate1)
 	(objectAtLocation Potato1 Pan3)
 	(objectAtLocation Pot1 CounterTop2)
 	(objectAtLocation DishSponge1 SinkBasin1)
 	(objectAtLocation Mug1 CounterTop3)
 	(objectAtLocation Pan1 Cabinet1)
 	(objectAtLocation Ladle2 Pot1)
 	(objectAtLocation Pot2 Fridge1)
 	(objectAtLocation ButterKnife1 Plate2)
 	(objectAtLocation Lettuce1 Fridge1)
 )
Output:
(:goal (and
        (objectAtLocation Egg1 DiningTable1)
        (objectAtLocation Egg2 DiningTable1)
        (objectAtLocation Potato1 DiningTable1)
        (isSliced Potato1)
        (isHot Egg1)
        (isHot Egg2)
        (isHot Potato1)
    )
)
****** Goal in Natural Language query ********
Write the goal specification in natural language.
Output:
(:goal (and
        (objectAtLocation Egg1 DiningTable1)
        (objectAtLocation Potato1 DiningTable1)
    )
)
******* Domain understanding query ********
What does "prepare a meal" mean? What are the relevant objects for preparing a meal?
Output:
(:goal (and 
        (inReceptacle Egg1 DiningTable1) 
        (inReceptacle Egg2 DiningTable1) 
        (inReceptacle Potato1 DiningTable1)
        (isSliced Potato1)
        (isCooked Egg1)
        (isCooked Egg2)
        (isCooked Potato1)
       )
)