
########### food_pre4 - 9 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Spoon1 - object)
 	(DishSponge1 - object)
 	(Spatula1 - object)
 	(PepperShaker1 - object)
 	(Bread1 - object)
 	(Pot1 - object)
 	(Potato1 - object)
 	(Egg1 - object)
 	(Cup1 - object)
 	(Apple1 - object)
 	(Egg2 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Microwave1 - receptacle)
 	(Pot3 - receptacle)
 	(Fridge2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(Plate1 - receptacle)
 	(Pot1 - receptacle)
 	(Microwave2 - receptacle)
 	(Pot2 - receptacle)
 	(Pot4 - receptacle)
 	(Lettuce1 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Bread1)
 	(sliceable Potato1)
 	(sliceable Egg1)
 	(sliceable Apple1)
 	(sliceable Egg2)
 	(heatable Bread1)
 	(heatable Potato1)
 	(heatable Egg1)
 	(heatable Cup1)
 	(heatable Apple1)
 	(heatable Egg2)
 	(coolable Bread1)
 	(coolable Potato1)
 	(coolable Egg1)
 	(coolable Apple1)
 	(coolable Egg2)
 	(objectAtLocation Spatula1 Pot1)
 	(objectAtLocation ButterKnife1 Bowl1)
 	(objectAtLocation PepperShaker1 CounterTop1)
 	(objectAtLocation Cup1 Microwave1)
 	(objectAtLocation DishSponge1 Pot2)
 	(objectAtLocation Apple1 Microwave2)
 	(objectAtLocation Potato1 Pot3)
 	(objectAtLocation Spoon1 Plate1)
 	(objectAtLocation Pot1 Fridge1)
 	(objectAtLocation Egg1 Pot4)
 	(objectAtLocation Bread1 Fridge2)
 	(objectAtLocation Egg2 SinkBasin1)
 	(objectAtLocation Lettuce1 Pot2)
 )
Output:
(:goal (and
                (objectAtLocation Bread1 DiningTable1)
                (objectAtLocation Potato1 DiningTable1)
                (objectAtLocation Egg1 DiningTable1)
                (objectAtLocation Apple1 DiningTable1)
                (objectAtLocation Egg2 DiningTable1)
                (objectAtLocation Cup1 DiningTable1)
            )
        )
****** Goal in Natural Language query ********
Write the goal specification in natural language.
Output:
(:goal (and
                (isSliced Bread1)
                (isSliced Potato1)
                (isSliced Apple1)
                (isSliced Egg1)
                (isSliced Egg2)
                (inReceptacle Bread1 DiningTable1)
                (inReceptacle Potato1 DiningTable1)
                (inReceptacle Apple1 DiningTable1)
                (inReceptacle Egg1 DiningTable1)
                (inReceptacle Egg2 DiningTable1)
                (isHot Potato1)
                (isHot Bread1)
                (isCool Apple1)
            )
        )
******* Domain understanding query ********
What does "prepare a meal" mean? What are the relevant objects for preparing a meal?
Output:
(:goal (and
        (isSliced Bread1)
        (isSliced Potato1)
        (isSliced Egg1)
        (isSliced Apple1)
        (isSliced Egg2)
        (isSliced Lettuce1)
        (isHot Bread1)
        (isHot Potato1)
        (isHot Egg1)
        (isHot Cup1)
        (isHot Apple1)
        (isHot Egg2)
        (isCool Bread1)
        (isCool Potato1)
        (isCool Egg1)
        (isCool Apple1)
        (isCool Egg2)
        (inReceptacle Bread1 DiningTable1)
        (inReceptacle Potato1 DiningTable1)
        (inReceptacle Egg1 DiningTable1)
        (inReceptacle Cup1 DiningTable1)
        (inReceptacle Apple1 DiningTable1)
        (inReceptacle Egg2 DiningTable1)
        (inReceptacle Lettuce1 DiningTable1)
    )
)