
########### food_pre4 - 17 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Spatula1 - object)
 	(PepperShaker1 - object)
 	(Bread1 - object)
 	(Tomato1 - object)
 	(Bowl1 - object)
 	(Pan1 - object)
 	(Potato1 - object)
 	(Egg1 - object)
 	(Apple2 - object)
 	(Mug1 - object)
 	(Apple1 - object)
 	(Potato2 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Cabinet3 - receptacle)
 	(Cabinet1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(StoveBurner1 - receptacle)
 	(Fridge2 - receptacle)
 	(Cabinet2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(Pot1 - receptacle)
 	(Cup1 - receptacle)
 	(GarbageCan2 - receptacle)
 	(Lettuce1 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Bread1)
 	(sliceable Tomato1)
 	(sliceable Potato1)
 	(sliceable Egg1)
 	(sliceable Apple2)
 	(sliceable Apple1)
 	(sliceable Potato2)
 	(heatable Bread1)
 	(heatable Tomato1)
 	(heatable Potato1)
 	(heatable Egg1)
 	(heatable Cup1)
 	(heatable Apple2)
 	(heatable Apple1)
 	(heatable Potato2)
 	(coolable Bread1)
 	(coolable Tomato1)
 	(coolable Potato1)
 	(coolable Egg1)
 	(coolable Apple2)
 	(coolable Apple1)
 	(coolable Potato2)
 	(objectAtLocation PepperShaker1 Cabinet1)
 	(objectAtLocation Tomato1 Fridge1)
 	(objectAtLocation Spatula1 Plate1)
 	(objectAtLocation Bread1 CounterTop1)
 	(objectAtLocation Mug1 Cabinet2)
 	(objectAtLocation Fork1 Cup1)
 	(objectAtLocation Potato1 SinkBasin1)
 	(objectAtLocation Potato2 GarbageCan1)
 	(objectAtLocation Apple1 Fridge2)
 	(objectAtLocation Pan1 StoveBurner1)
 	(objectAtLocation Egg1 Pot1)
 	(objectAtLocation Apple2 GarbageCan2)
 	(objectAtLocation Bowl1 Cabinet3)
 	(objectAtLocation Lettuce1 Cabinet3)
 )
Output:
(:goal (and
        (objectAtLocation Bread1 DiningTable1)
        (objectAtLocation Tomato1 DiningTable1)
        (objectAtLocation Potato1 DiningTable1)
        (objectAtLocation Egg1 DiningTable1)
        (objectAtLocation Apple2 DiningTable1)
        (objectAtLocation Apple1 DiningTable1)
        (objectAtLocation Potato2 DiningTable1)
        (objectAtLocation Lettuce1 DiningTable1)
    )
)
****** Goal in Natural Language query ********
Write the goal specification in natural language.
Output:
(:goal (and
                (isSliced Bread1)
                (isSliced Tomato1)
                (isSliced Potato1)
                (isSliced Egg1)
                (isSliced Apple1)
                (isSliced Potato2)
                (isSliced Lettuce1)
                (isHot Bread1)
                (isHot Tomato1)
                (isHot Potato1)
                (isHot Egg1)
                (isHot Apple1)
                (isHot Potato2)
                (objectAtLocation Bread1 DiningTable1)
                (objectAtLocation Tomato1 DiningTable1)
                (objectAtLocation Potato1 DiningTable1)
                (objectAtLocation Egg1 DiningTable1)
                (objectAtLocation Apple1 DiningTable1)
                (objectAtLocation Potato2 DiningTable1)
                (objectAtLocation Lettuce1 DiningTable1)
            )
        )
******* Domain understanding query ********
What does "prepare a meal" mean? What are the relevant objects for preparing a meal?
Output:
(:goal (and
        (objectAtLocation Bread1 DiningTable1)
        (objectAtLocation Tomato1 DiningTable1)
        (objectAtLocation Potato1 DiningTable1)
        (objectAtLocation Egg1 DiningTable1)
        (objectAtLocation Apple2 DiningTable1)
        (objectAtLocation Apple1 DiningTable1)
        (objectAtLocation Potato2 DiningTable1)
        (objectAtLocation Lettuce1 DiningTable1)
    )
)