
########### scene4 - 18 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Knife1 - object)
 	(Tomato1 - object)
 	(Plate1 - object)
 	(Ladle1 - object)
 	(Pot1 - object)
 	(Potato1 - object)
 	(Egg1 - object)
 	(Mug1 - object)
 	(Egg2 - object)
 	(Potato2 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Cabinet1 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(Pot1 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Plate2 - receptacle)
 	(Pot2 - receptacle)
 	(Cup1 - object)
 	(Bowl1 - object)
 	(Fork1 - object)
 	(Spoon1 - object)
 	(Cup2 - object)
 	(Bowl2 - object)
 	(Plate2 - object)
 	(Fork2 - object)
 	(Spoon2 - object)
 	(Knife2 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Tomato1)
 	(sliceable Potato1)
 	(sliceable Egg1)
 	(sliceable Egg2)
 	(sliceable Potato2)
 	(heatable Tomato1)
 	(heatable Potato1)
 	(heatable Egg1)
 	(heatable Egg2)
 	(heatable Potato2)
 	(coolable Tomato1)
 	(coolable Potato1)
 	(coolable Egg1)
 	(coolable Egg2)
 	(coolable Potato2)
 	(objectAtLocation Ladle1 Pot1)
 	(objectAtLocation Egg1 Pot2)
 	(objectAtLocation Plate1 Fridge1)
 	(objectAtLocation Egg2 CounterTop1)
 	(objectAtLocation Pot1 Cabinet1)
 	(objectAtLocation Mug1 Plate1)
 	(objectAtLocation Tomato1 SinkBasin1)
 	(objectAtLocation Potato1 Plate2)
 	(objectAtLocation Knife1 CounterTop2)
 	(objectAtLocation Potato2 SinkBasin2)
 	(objectAtLocation Cup1 CounterTop1)
 	(objectAtLocation Bowl1 Pot1)
 	(objectAtLocation Fork1 CounterTop1)
 	(objectAtLocation Spoon1 Plate2)
 	(objectAtLocation Cup2 Cabinet1)
 	(objectAtLocation Bowl2 Cabinet1)
 	(objectAtLocation Fork2 Cabinet1)
 	(objectAtLocation Spoon2 SinkBasin1)
 	(objectAtLocation Knife2 Plate1)
 )
Output:
(:goal (and
    (objectAtLocation Plate1 DiningTable1)
    (objectAtLocation Plate2 DiningTable1)
    (objectAtLocation Fork1 DiningTable1)
    (objectAtLocation Fork2 DiningTable1)
    (objectAtLocation Knife1 DiningTable1)
    (objectAtLocation Knife2 DiningTable1)
    (objectAtLocation Spoon1 DiningTable1)
    (objectAtLocation Spoon2 DiningTable1)
    (objectAtLocation Cup1 DiningTable1)
    (objectAtLocation Cup2 DiningTable1)
))