
########### scene4 - 13 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Spoon1 - object)
 	(Spatula2 - object)
 	(Spatula1 - object)
 	(PepperShaker1 - object)
 	(Knife1 - object)
 	(Tomato1 - object)
 	(PepperShaker2 - object)
 	(Bowl1 - object)
 	(ButterKnife2 - object)
 	(Egg1 - object)
 	(Cup1 - object)
 	(Mug1 - object)
 	(Apple1 - object)
 	(Egg2 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Cabinet1 - receptacle)
 	(Mug1 - receptacle)
 	(Plate2 - receptacle)
 	(SinkBasin4 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(SinkBasin3 - receptacle)
 	(Pot1 - receptacle)
 	(Plate1 - receptacle)
 	(SinkBasin2 - receptacle)
 	(CoffeeMachine1 - receptacle)
 	(Pot2 - receptacle)
 	(Pan1 - receptacle)
 	(Plate1 - object)
 	(Fork1 - object)
 	(Cup2 - object)
 	(Bowl2 - object)
 	(Plate2 - object)
 	(Fork2 - object)
 	(Spoon2 - object)
 	(Knife2 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Egg1)
 	(sliceable Tomato1)
 	(sliceable Egg2)
 	(sliceable Apple1)
 	(heatable Tomato1)
 	(heatable Egg1)
 	(heatable Cup1)
 	(heatable Apple1)
 	(heatable Egg2)
 	(coolable Egg1)
 	(coolable Tomato1)
 	(coolable Egg2)
 	(coolable Apple1)
 	(objectAtLocation Bowl1 SinkBasin1)
 	(objectAtLocation ButterKnife1 CounterTop1)
 	(objectAtLocation Tomato1 Pot1)
 	(objectAtLocation ButterKnife2 Pot2)
 	(objectAtLocation Egg1 Bowl1)
 	(objectAtLocation Egg2 Pan1)
 	(objectAtLocation Mug1 CoffeeMachine1)
 	(objectAtLocation Spatula1 SinkBasin2)
 	(objectAtLocation Apple1 SinkBasin3)
 	(objectAtLocation PepperShaker1 CounterTop2)
 	(objectAtLocation Cup1 SinkBasin4)
 	(objectAtLocation PepperShaker2 Cabinet1)
 	(objectAtLocation Knife1 Mug1)
 	(objectAtLocation Spoon1 Plate1)
 	(objectAtLocation Spatula2 Plate2)
 	(objectAtLocation Fork1 Plate1)
 	(objectAtLocation Cup2 Plate2)
 	(objectAtLocation Bowl2 Pot2)
 	(objectAtLocation Fork2 CoffeeMachine1)
 	(objectAtLocation Spoon2 SinkBasin4)
 	(objectAtLocation Knife2 Cabinet1)
 )
Output:
(:goal (and
            (objectAtLocation Plate1 DiningTable1)
            (objectAtLocation Plate2 DiningTable1)
            (objectAtLocation Fork1 DiningTable1)
            (objectAtLocation Fork2 DiningTable1)
            (objectAtLocation Knife1 DiningTable1)
            (objectAtLocation Knife2 DiningTable1)
            (objectAtLocation Spoon1 DiningTable1)
            (objectAtLocation Spoon2 DiningTable1)
            (objectAtLocation Cup1 DiningTable1)
            (objectAtLocation Cup2 DiningTable1)
        )
)