
########### scene4 - 6 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Tomato2 - object)
 	(Spoon1 - object)
 	(Knife1 - object)
 	(Potato2 - object)
 	(Bread1 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Bowl1 - object)
 	(Pan1 - object)
 	(Pot1 - object)
 	(Potato1 - object)
 	(Cup1 - object)
 	(Mug1 - object)
 	(Apple1 - object)
 	(ButterKnife1 - object)
 	(Fridge1 - receptacle)
 	(Pan2 - receptacle)
 	(Cabinet1 - receptacle)
 	(StoveBurner1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Pot2 - receptacle)
 	(Microwave1 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(Plate1 - receptacle)
 	(Pot1 - receptacle)
 	(SinkBasin2 - receptacle)
 	(CoffeeMachine1 - receptacle)
 	(Mug1 - receptacle)
 	(Pan1 - receptacle)
 	(Plate1 - object)
 	(Fork1 - object)
 	(Cup2 - object)
 	(Bowl2 - object)
 	(Plate2 - object)
 	(Fork2 - object)
 	(Spoon2 - object)
 	(Knife2 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Tomato2)
 	(sliceable Bread1)
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Potato1)
 	(sliceable Apple1)
 	(sliceable Potato2)
 	(heatable Tomato2)
 	(heatable Bread1)
 	(heatable Tomato1)
 	(heatable Potato1)
 	(heatable Cup1)
 	(heatable Apple1)
 	(heatable Potato2)
 	(coolable Tomato2)
 	(coolable Bread1)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Potato1)
 	(coolable Apple1)
 	(coolable Potato2)
 	(objectAtLocation Pot1 StoveBurner1)
 	(objectAtLocation Cup1 Fridge1)
 	(objectAtLocation Lettuce1 Bowl1)
 	(objectAtLocation Bowl1 Cabinet1)
 	(objectAtLocation Knife1 Pan1)
 	(objectAtLocation Apple1 Pot1)
 	(objectAtLocation Tomato1 Pan2)
 	(objectAtLocation Spoon1 Mug1)
 	(objectAtLocation Mug1 CoffeeMachine1)
 	(objectAtLocation ButterKnife1 SinkBasin1)
 	(objectAtLocation Pan1 SinkBasin2)
 	(objectAtLocation Potato1 GarbageCan1)
 	(objectAtLocation Potato2 Plate1)
 	(objectAtLocation Tomato2 Pot2)
 	(objectAtLocation Bread1 Microwave1)
 	(objectAtLocation Fork1 Pan2)
 	(objectAtLocation Cup2 SinkBasin2)
 	(objectAtLocation Bowl2 Cabinet1)
 	(objectAtLocation Plate2 Bowl1)
 	(objectAtLocation Fork2 CoffeeMachine1)
 	(objectAtLocation Spoon2 Pot2)
 	(objectAtLocation Knife2 Pan2)
 )
Output:
(:goal (and
        (objectAtLocation Plate1 DiningTable1)
        (objectAtLocation Plate2 DiningTable1)
        (objectAtLocation Fork1 DiningTable1)
        (objectAtLocation Fork2 DiningTable1)
        (objectAtLocation Knife1 DiningTable1)
        (objectAtLocation Knife2 DiningTable1)
        (objectAtLocation Spoon1 DiningTable1)
        (objectAtLocation Spoon2 DiningTable1)
        (objectAtLocation Cup1 DiningTable1)
        (objectAtLocation Cup2 DiningTable1)
    )
)