
########### scene4 - 15 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Tomato2 - object)
 	(Lettuce2 - object)
 	(DishSponge1 - object)
 	(SoapBottle1 - object)
 	(Plate2 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Plate1 - object)
 	(Ladle1 - object)
 	(Potato1 - object)
 	(Egg1 - object)
 	(Mug1 - object)
 	(Apple1 - object)
 	(SaltShaker1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Cabinet3 - receptacle)
 	(Cabinet1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(CounterTop3 - receptacle)
 	(Microwave1 - receptacle)
 	(CounterTop2 - receptacle)
 	(Cabinet2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(Pot1 - receptacle)
 	(Microwave3 - receptacle)
 	(Microwave2 - receptacle)
 	(Cup1 - object)
 	(Bowl1 - object)
 	(Fork1 - object)
 	(Spoon1 - object)
 	(Knife1 - object)
 	(Cup2 - object)
 	(Bowl2 - object)
 	(Fork2 - object)
 	(Spoon2 - object)
 	(Knife2 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Tomato2)
 	(sliceable Lettuce2)
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Potato1)
 	(sliceable Egg1)
 	(sliceable Apple1)
 	(heatable Tomato2)
 	(heatable Tomato1)
 	(heatable Potato1)
 	(heatable Egg1)
 	(heatable Apple1)
 	(coolable Tomato2)
 	(coolable Lettuce2)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Potato1)
 	(coolable Egg1)
 	(coolable Apple1)
 	(objectAtLocation DishSponge1 Pot1)
 	(objectAtLocation SaltShaker1 Cabinet1)
 	(objectAtLocation Egg1 GarbageCan1)
 	(objectAtLocation Ladle1 CounterTop1)
 	(objectAtLocation Plate1 Microwave1)
 	(objectAtLocation Lettuce1 Bowl1)
 	(objectAtLocation Tomato1 Fridge1)
 	(objectAtLocation Lettuce2 SinkBasin1)
 	(objectAtLocation Potato1 CounterTop2)
 	(objectAtLocation SoapBottle1 Cabinet2)
 	(objectAtLocation Plate2 Cabinet3)
 	(objectAtLocation Apple1 CounterTop3)
 	(objectAtLocation Tomato2 Microwave2)
 	(objectAtLocation Mug1 Microwave3)
 	(objectAtLocation Cup1 Cabinet1)
 	(objectAtLocation Fork1 CounterTop1)
 	(objectAtLocation Spoon1 CounterTop2)
 	(objectAtLocation Knife1 Fridge1)
 	(objectAtLocation Cup2 Cabinet2)
 	(objectAtLocation Bowl2 Cabinet2)
 	(objectAtLocation Fork2 Cabinet2)
 	(objectAtLocation Spoon2 Microwave2)
 	(objectAtLocation Knife2 Microwave2)
 )
Output:
(:goal (and
    (objectAtLocation Plate1 DiningTable1)
    (objectAtLocation Plate2 DiningTable1)
    (objectAtLocation Fork1 DiningTable1)
    (objectAtLocation Fork2 DiningTable1)
    (objectAtLocation Knife1 DiningTable1)
    (objectAtLocation Knife2 DiningTable1)
    (objectAtLocation Spoon1 DiningTable1)
    (objectAtLocation Spoon2 DiningTable1)
    (objectAtLocation Cup1 DiningTable1)
    (objectAtLocation Cup2 DiningTable1)
))