
########### scene4 - 19 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Spoon1 - object)
 	(Spatula1 - object)
 	(Knife1 - object)
 	(Bread1 - object)
 	(Bread2 - object)
 	(Spoon2 - object)
 	(Plate1 - object)
 	(Ladle1 - object)
 	(Pot1 - object)
 	(ButterKnife2 - object)
 	(Potato1 - object)
 	(Mug1 - object)
 	(SaltShaker1 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Cabinet1 - receptacle)
 	(StoveBurner1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Microwave1 - receptacle)
 	(CounterTop2 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Plate1 - receptacle)
 	(Pot1 - receptacle)
 	(Microwave2 - receptacle)
 	(SinkBasin2 - receptacle)
 	(Cup1 - receptacle)
 	(Mug1 - receptacle)
 	(Pan1 - receptacle)
 	(Cup1 - object)
 	(Bowl1 - object)
 	(Fork1 - object)
 	(Cup2 - object)
 	(Bowl2 - object)
 	(Plate2 - object)
 	(Fork2 - object)
 	(Knife2 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Bread2)
 	(sliceable Bread1)
 	(sliceable Potato1)
 	(heatable Bread2)
 	(heatable Cup1)
 	(heatable Bread1)
 	(heatable Potato1)
 	(coolable Bread2)
 	(coolable Bread1)
 	(coolable Potato1)
 	(objectAtLocation Pot1 StoveBurner1)
 	(objectAtLocation Bread1 Microwave1)
 	(objectAtLocation ButterKnife1 CounterTop1)
 	(objectAtLocation Ladle1 Plate1)
 	(objectAtLocation Mug1 Microwave2)
 	(objectAtLocation ButterKnife2 Pot1)
 	(objectAtLocation Knife1 Mug1)
 	(objectAtLocation Spoon1 Pan1)
 	(objectAtLocation Potato1 SinkBasin1)
 	(objectAtLocation SaltShaker1 CounterTop2)
 	(objectAtLocation Spatula1 SinkBasin2)
 	(objectAtLocation Spoon2 Cup1)
 	(objectAtLocation Bread2 GarbageCan1)
 	(objectAtLocation Plate1 Cabinet1)
 	(objectAtLocation Bowl1 SinkBasin2)
 	(objectAtLocation Fork1 SinkBasin2)
 	(objectAtLocation Cup2 CounterTop1)
 	(objectAtLocation Bowl2 Mug1)
 	(objectAtLocation Plate2 SinkBasin1)
 	(objectAtLocation Fork2 StoveBurner1)
 	(objectAtLocation Knife2 Microwave1)
 )
Output:
(:goal (and
            (objectAtLocation Plate1 DiningTable1)
            (objectAtLocation Plate2 DiningTable1)
            (objectAtLocation Fork1 DiningTable1)
            (objectAtLocation Fork2 DiningTable1)
            (objectAtLocation Knife1 DiningTable1)
            (objectAtLocation Knife2 DiningTable1)
            (objectAtLocation Cup1 DiningTable1)
            (objectAtLocation Cup2 DiningTable1)
        )
)