
########### scene4 - 14 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Fork1 - object)
 	(Cup1 - object)
 	(Bread1 - object)
 	(Lettuce1 - object)
 	(Bowl1 - object)
 	(Pot1 - object)
 	(ButterKnife1 - object)
 	(Fork2 - object)
 	(Pot2 - object)
 	(Apple1 - object)
 	(Fork3 - object)
 	(Fridge1 - receptacle)
 	(Mug2 - receptacle)
 	(Fridge3 - receptacle)
 	(Fridge2 - receptacle)
 	(Microwave1 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(Bowl2 - receptacle)
 	(Pot1 - receptacle)
 	(Mug1 - receptacle)
 	(Pan1 - receptacle)
 	(Plate1 - object)
 	(Spoon1 - object)
 	(Knife1 - object)
 	(Cup2 - object)
 	(Bowl2 - object)
 	(Plate2 - object)
 	(Spoon2 - object)
 	(Knife2 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Bread1)
 	(sliceable Lettuce1)
 	(sliceable Apple1)
 	(heatable Cup1)
 	(heatable Bread1)
 	(heatable Apple1)
 	(coolable Bread1)
 	(coolable Lettuce1)
 	(coolable Apple1)
 	(objectAtLocation Fork1 Pot1)
 	(objectAtLocation Pot1 Fridge1)
 	(objectAtLocation Fork2 Mug1)
 	(objectAtLocation ButterKnife1 Mug2)
 	(objectAtLocation Fork3 Pan1)
 	(objectAtLocation Bowl1 Fridge2)
 	(objectAtLocation Bread1 Fridge3)
 	(objectAtLocation Lettuce1 Bowl1)
 	(objectAtLocation Cup1 Microwave1)
 	(objectAtLocation Apple1 Bowl2)
 	(objectAtLocation Pot2 SinkBasin1)
 	(objectAtLocation Plate1 Microwave1)
 	(objectAtLocation Spoon1 Pot1)
 	(objectAtLocation Knife1 Mug1)
 	(objectAtLocation Cup2 Mug1)
 	(objectAtLocation Plate2 Bowl2)
 	(objectAtLocation Spoon2 Fridge3)
 	(objectAtLocation Knife2 Pot1)
 )
Output:
(:goal (and
            (objectAtLocation Spoon1 DiningTable1)
            (objectAtLocation Fork1 DiningTable1)
            (objectAtLocation Knife1 DiningTable1)
            (objectAtLocation Plate1 DiningTable1)
            (objectAtLocation Cup1 DiningTable1)
            (objectAtLocation Spoon2 DiningTable1)
            (objectAtLocation Fork2 DiningTable1)
            (objectAtLocation Knife2 DiningTable1)
            (objectAtLocation Plate2 DiningTable1)
            (objectAtLocation Cup2 DiningTable1)
        )
)