
########### scene4 - 2 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Spoon1 - object)
 	(DishSponge1 - object)
 	(Knife1 - object)
 	(Lettuce1 - object)
 	(Tomato1 - object)
 	(Ladle1 - object)
 	(Pot1 - object)
 	(Potato1 - object)
 	(Egg1 - object)
 	(Cup1 - object)
 	(Mug1 - object)
 	(CounterTop1 - receptacle)
 	(Fridge1 - receptacle)
 	(Pan2 - receptacle)
 	(Cabinet1 - receptacle)
 	(GarbageCan1 - receptacle)
 	(Cabinet2 - receptacle)
 	(Bowl1 - receptacle)
 	(Plate1 - receptacle)
 	(Plate2 - receptacle)
 	(Cup1 - receptacle)
 	(Pan1 - receptacle)
 	(Bowl1 - object)
 	(Plate1 - object)
 	(Fork1 - object)
 	(Cup2 - object)
 	(Bowl2 - object)
 	(Plate2 - object)
 	(Fork2 - object)
 	(Spoon2 - object)
 	(Knife2 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Egg1)
 	(sliceable Lettuce1)
 	(sliceable Tomato1)
 	(sliceable Potato1)
 	(heatable Egg1)
 	(heatable Cup1)
 	(heatable Tomato1)
 	(heatable Potato1)
 	(coolable Egg1)
 	(coolable Lettuce1)
 	(coolable Tomato1)
 	(coolable Potato1)
 	(objectAtLocation Egg1 GarbageCan1)
 	(objectAtLocation Knife1 Plate1)
 	(objectAtLocation Ladle1 Bowl1)
 	(objectAtLocation Spoon1 Cup1)
 	(objectAtLocation Pot1 Fridge1)
 	(objectAtLocation Tomato1 Pan1)
 	(objectAtLocation Cup1 Cabinet1)
 	(objectAtLocation Mug1 Cabinet2)
 	(objectAtLocation Potato1 Pan2)
 	(objectAtLocation DishSponge1 Plate2)
 	(objectAtLocation Lettuce1 CounterTop1)
 	(objectAtLocation Fork1 Pan1)
 	(objectAtLocation Cup2 Cabinet2)
 	(objectAtLocation Bowl2 Cabinet2)
 	(objectAtLocation Fork2 GarbageCan1)
 	(objectAtLocation Spoon2 Pan1)
 	(objectAtLocation Knife2 Plate2)
 )
Output:
(:goal (and
            (objectAtLocation Plate1 DiningTable1)
            (objectAtLocation Plate2 DiningTable1)
            (objectAtLocation Fork1 DiningTable1)
            (objectAtLocation Fork2 DiningTable1)
            (objectAtLocation Knife1 DiningTable1)
            (objectAtLocation Knife2 DiningTable1)
            (objectAtLocation Spoon1 DiningTable1)
            (objectAtLocation Spoon2 DiningTable1)
            (objectAtLocation Cup1 DiningTable1)
            (objectAtLocation Cup2 DiningTable1)
        )
)