
########### scene4 - 7 ##########

******* problem file for debug *********
(:objects 
 	(agent1 - agent)
 	(Tomato2 - object)
 	(Tomato3 - object)
 	(Spatula2 - object)
 	(Spatula1 - object)
 	(Potato2 - object)
 	(Tomato1 - object)
 	(Plate1 - object)
 	(Pan1 - object)
 	(Potato1 - object)
 	(Apple2 - object)
 	(Mug1 - object)
 	(Apple1 - object)
 	(ButterKnife1 - object)
 	(CounterTop1 - receptacle)
 	(Pan2 - receptacle)
 	(Cabinet1 - receptacle)
 	(Microwave1 - receptacle)
 	(Pot3 - receptacle)
 	(SinkBasin1 - receptacle)
 	(Bowl1 - receptacle)
 	(Pot1 - receptacle)
 	(Microwave2 - receptacle)
 	(Cup1 - receptacle)
 	(CoffeeMachine1 - receptacle)
 	(Pot2 - receptacle)
 	(Pan1 - receptacle)
 	(Cup1 - object)
 	(Bowl1 - object)
 	(Fork1 - object)
 	(Spoon1 - object)
 	(Knife1 - object)
 	(Cup2 - object)
 	(Bowl2 - object)
 	(Plate2 - object)
 	(Fork2 - object)
 	(Spoon2 - object)
 	(Knife2 - object)
 	(DiningTable1 - receptacle)
 )
(:init 
 	(sliceable Tomato2)
 	(sliceable Tomato3)
 	(sliceable Tomato1)
 	(sliceable Potato1)
 	(sliceable Apple2)
 	(sliceable Apple1)
 	(sliceable Potato2)
 	(heatable Tomato2)
 	(heatable Tomato3)
 	(heatable Tomato1)
 	(heatable Potato1)
 	(heatable Cup1)
 	(heatable Apple2)
 	(heatable Apple1)
 	(heatable Potato2)
 	(coolable Tomato2)
 	(coolable Tomato3)
 	(coolable Tomato1)
 	(coolable Potato1)
 	(coolable Apple2)
 	(coolable Apple1)
 	(coolable Potato2)
 	(objectAtLocation Tomato1 Pot1)
 	(objectAtLocation Potato1 Pot2)
 	(objectAtLocation Tomato2 Bowl1)
 	(objectAtLocation Tomato3 CounterTop1)
 	(objectAtLocation Apple1 Microwave1)
 	(objectAtLocation Plate1 Microwave2)
 	(objectAtLocation Mug1 CoffeeMachine1)
 	(objectAtLocation Spatula1 Pan1)
 	(objectAtLocation Pan1 Cabinet1)
 	(objectAtLocation ButterKnife1 Cup1)
 	(objectAtLocation Potato2 SinkBasin1)
 	(objectAtLocation Apple2 Pan2)
 	(objectAtLocation Spatula2 Pot3)
 	(objectAtLocation Fork1 Cup1)
 	(objectAtLocation Spoon1 Microwave2)
 	(objectAtLocation Knife1 Bowl1)
 	(objectAtLocation Cup2 Bowl1)
 	(objectAtLocation Bowl2 Pot1)
 	(objectAtLocation Plate2 Microwave2)
 	(objectAtLocation Fork2 SinkBasin1)
 	(objectAtLocation Spoon2 Pot2)
 	(objectAtLocation Knife2 Pot3)
 )
Output:
(:goal (and
    (objectAtLocation Plate1 DiningTable1)
    (objectAtLocation Fork1 DiningTable1)
    (objectAtLocation Knife1 DiningTable1)
    (objectAtLocation Spoon1 DiningTable1)
    (objectAtLocation Cup1 DiningTable1)
    (objectAtLocation Plate2 DiningTable1)
    (objectAtLocation Fork2 DiningTable1)
    (objectAtLocation Knife2 DiningTable1)
    (objectAtLocation Spoon2 DiningTable1)
    (objectAtLocation Cup2 DiningTable1)
))